### ISSUE TITLE
Type checking via Flow

### ISSUE THREAD

**Issue by trentgrover-wf** [facebook/fixed-data-table#10]
I notice that this code doesn't include `@flow`, but it does have `@typechecks`.  Is this something related to Facebook's internal type checking system?

**Comment by pieterv** [comment]
Yes this is used for Facebook's internal runtime type checking system which predates Flow (you will notice the React codebase has these tags well), the intention is to upgrade this to Flow at some point. It would be awesome if the community could contribute to this as well!

**Comment by pieterv** [comment]
We have started adding some basic flow typed code, when we update code we will make sure it is typed.
