### ISSUE TITLE
Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by hipertracker** [facebook/fixed-data-table#104]
I try to use FixedDataTable from simple example at http://facebook.github.io/fixed-data-table/. For my [component](https://github.com/hipertracker/react-embed/blob/master/app/components/DataTable.js) I get the following error:

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by pieterv** [comment]
Hey @hipertracker i assume you got this going, the repo seems to be working fine for me. Pretty sweet demo as well!

![image](https://cloud.githubusercontent.com/assets/438482/7739714/b0bbb2fe-ff1a-11e4-9596-5d7fca7892e2.png)
