### ISSUE TITLE
Rerender headers as well when data has changed

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#109]
I think since v0.1.1 or v.0.1.2 I see the warning

```
Warning: Failed propType: Invalid prop `label` of type `boolean` supplied to `FixedDataTableColumn`, expected `string`.
```

which makes sense to me. But before that, I "abused" the label to force a re-render of the table header when an app-specific state has changed. 

But now, with that warning, I do not want to abuse the label anymore.

Here the full story:

The outer most left column has checkboxes only and their header is labelled as "Select All" with a checkbox in the header. Whenever I click on that header checkbox, all rows are selected.

I did it like that

```coffee
    <Table
      height             = {@props.height}
      width              = {@props.width}
      rowGetter          = {@_getRow}
      rowClassNameGetter = {@_getRowClass}
      rowsCount          = {@_currentPageResults().length}
      columns            = {[
        {
          # Set label to selected value to force render on change.
          label:          @_areAllSelected()
          dataKey:        'selected'
          width:          26
          align:          'center'
          headerRenderer: @_renderSelectAll
          cellRenderer:   @_renderSelect
        }
        {
          label:         'Sender'
          dataKey:       'sender'
          width:         120
          flexGrow:      1
          isResizable:   true
          cellRenderer:  @_renderSender
          cellClassName: 'truncate-cell'
        }
        ...
      ]}
```

and

```coffee
  _renderSelectAll: (allSelected) ->
    <input
      type     = "checkbox"
      checked  = {allSelected} # here I abuse the label and treat it like data
      onChange = {@_onSelectAllChange}
    />
```

What change do you suggest to make this warning disappear?

At the moment it seems that the headers are not re-rendered when row data has changed, i.E. when all is selected in one go when `_onSelectAllChange()` has been called.

Suggestions very welcome. Not sure if it's a bug, a feature request or if I'm doing something wrong here.

**Comment by pieterv** [comment]
For this use case you can use the `headerDataGetter` on the Table component  to return the relevant data into the headerRenderer :)

**Comment by binarykitchen** [comment]
Ah, beautiful, works. Thanks!

**Comment by Andreyco** [comment]
Very same issue over here https://github.com/facebook/fixed-data-table/issues/71#issuecomment-92318922

**Comment by binarykitchen** [comment]
Hmmm, I realized there is one problem: when I define a `headerDataGetter`, then the labels I have defined in the `columns[]` props will be ignored.

**Comment by binarykitchen** [comment]
I think, adding a second parameter at https://github.com/facebook/fixed-data-table/blob/f66c616a3d03ea0bc88f2e32b6cbb0cd93edde98/dist/fixed-data-table.js#L1051 would solve my problem.

Something like that

```js
if (this.props.headerDataGetter) {
  headData[columnProps.dataKey] =
    this.props.headerDataGetter(columnProps.dataKey, columnProps);
} else {
  headData[columnProps.dataKey] = columnProps.label || '';
}
```

**Comment by airwin** [comment]
I need the 2nd param too mentions in @binarykitchen 's code . @pieterv

**Comment by box-turtle** [comment]
+1 for binarykitchen's suggestion.

**Comment by puzzfuzz** [comment]
+1 as well. I've got a dynamic list of columns where I need to have the dataKey be an index, but I won't have access to the label. I'd like to show a "sorted ASC v. DESC" treatment on the header and do this in `headerRenderer`, however that doesn't get called if the header data doesn't change. `headerDataGetter` getting the column props in the signature would solve this nicely.
