### ISSUE TITLE
:question - Would Scrollbar.react.js and ReactWheelHandler.jsx be a good place to put touch events?

### ISSUE THREAD

**Issue by christopherbalz** [facebook/fixed-data-table#111]
For example, in Scrollbar, adding them to the 'div' right alongside the mouse . . . and then mapping them into the mouse (non-touch) methods (compute the delta from the `TouchList` for `touchmove`, and so forth)?  

Would the same approach work well in ReactWheelHandler.jsx?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by christopherbalz** [comment]
Resolved.
