### ISSUE TITLE
Default style is too fancy

### ISSUE THREAD

**Issue by Andreyco** [facebook/fixed-data-table#113]
Would you consider placing clean CSS as default?
One which contains bare minimum of styling data, required component to work.
One, which does not need to be overridden.

Current one might be included as "theme" CSS.

I am cleaning it right now. I will send PR if you accept the idea.

**Comment by pieterv** [comment]
Hey @Andreyco, PR would be awesome! This is definitely something we want, we just haven't had the time to do it.

So the way we have thought about approaching this is to split out layout specific css and styling "theme" css. The layout styles should include anything that is required to make the table function/ position correctly (like you described). With the "theme" being everything else including borders and such. Ideally we would split the current stylesheets in two different css files for each one and create different classes for both the styling hooks and the layout. In the long term we see the layout styles being included as inline CSS in the react component but we don't think our tooling this ready for this yet, with this in mind it makes splitting the class names out more important so its easier to remove and pull the style inline in the future :)

Let me know of you have any questions or need any help.

cc @jbonta Do you have any other thoughts on this?

**Comment by jbonta** [comment]
Yeah, this is exactly what we're hoping for. I think the main thing to be careful of here is our dependency on border widths for computing all the dimensions. A logical first step might be to simplify everything except borders, maybe just using `border-color: transparent` if we have to. Once we are rolling with this separation (default + theme), we can maybe kill some additional border logic or make better use of `box-sizing: border-box;`

**Comment by Andreyco** [comment]
Hi guys. I separated stylesheets.

Visual styling is now in separate file. There is no problem with borders. Default style applies transparent border to everything having border defined.

I had no additional time to dig into Webpack. Due to this fact `build-dist` script generates two JS files (regular & minified) for theme, which are completely redundant. I'd like to ask you for help with configuring build script here.

**Comment by ehzhang** [comment]
Closing, as addressed by PR #121. Woo!

**Comment by Andreyco** [comment]
Lovely!

**Comment by tonyxiao** [comment]
Even in default setting fixed-data-table still includes borders. 

![image](https://cloud.githubusercontent.com/assets/696842/18812069/83e5eede-827c-11e6-8b3e-ad416cd989ed.png)

Any reason against removing border-style from fixed-data-tables-base? https://github.com/facebook/fixed-data-table/blob/0c8a7d1317077e788eae619a245bd77b09c0bf1c/src/css/layout/fixedDataTableLayout.css#L13-L14

**Comment by Andreyco** [comment]
@tonyxiao honestly, table does not have to contain borders in every case. Default style should be as clean as possible to prevent *any* style overrides.
