### ISSUE TITLE
onScroll event not supported

### ISSUE THREAD

**Issue by DanielMiddleton** [facebook/fixed-data-table#116]
I am trying to implement a smooth infinite scroll, where new items are loaded into my table as the user is scrolling. I can use the onScrollEnd event to load items in when scrolling stops, but ideally I wouldn't have to wait for that.

Is it possible to add support for this event? Is there something prohibitive about it - obviously it could be misused, but is it just untenable in general? Am I just going about this completely wrong, and there's a better way to do what I want that's already supported?

Thanks

**Comment by pieterv** [comment]
Hey @DanielMiddleton the table handles most of this logic for you and will call the `rowGetter` function as the rows get close to being in view, the one key thing is you will need to give it an absolute number of rows so the scollbar size can be estimated but you can update the value over time as you get more data. Here is an example of how this can be implemented http://jsbin.com/temufa/8/edit?html,js,output)

**Comment by DanielMiddleton** [comment]
Oh, I see. That example is great, that's what I needed. Thanks

**Comment by eriknyk** [comment]
is there another way to implement infiniteScroll?
the @pieterv is a good impl. still it seems it is not enough, can we attach some callback to the the onScroll event or something else?
