### ISSUE TITLE
Accessibility plans?

### ISSUE THREAD

**Issue by egauci** [facebook/fixed-data-table#117]
I just realized this code doesn't actually create HTML tables. Is it accessible to assistive technology?

**Comment by jbonta** [comment]
@egauci - Unfortunately using a real `table` proved to be all but impossible in our first attempts to make this UI with fixed columns. Accessibility is high on our list of things we'd like to add. Fortunately, with ARIA, we expect to be able to provide pretty comprehensive hints that the data is tabular and columnar, etc. In our next release, we're hoping to re-think source ordering to make this even better for SEO and assistive readers. In the meantime, we always welcome patches to make this project better!

**Comment by egauci** [comment]
Yes, I understand the issues with using HTML tables for this. One approach that's promising is to make the entire left structure aria-hidden=true then replicating the fixed columns within the scrolling table as visually hidden. It's not a perfect solution either.

I'm glad to hear you're thinking of accessibility. Thank you for answering.
