### ISSUE TITLE
Can't get fixed data table to work

### ISSUE THREAD

**Issue by songz** [facebook/fixed-data-table#12]
If I install from npm, I get #11 error.
If I install from github via `npm install --save git+https://github.com/facebook/fixed-data-table`, I get the following error: `Error: Cannot find module './internal/FixedDataTableRoot' from '/Users/szhen2/Documents/app/node_modules/fixed-data-table'`

I'm using the sample code provided in the [homepage](http://facebook.github.io/fixed-data-table/)

**Comment by pieterv** [comment]
see #11, If you want to run the code from github you need to build the repo first via `npm install && npm run build-npm`
