### ISSUE TITLE
Object function Object() { [native code] } has no method 'assign'

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#120]
Happens when I run a jest rest with it

```
node_modules/fixed-data-table/internal/FixedDataTableCell.react.js: Object function Object() { [native code] } has no method 'assign'
    at Function.ImmutableValue.mergeAllPropertiesInto (node_modules/fixed-data-table/internal/ImmutableValue.js:65:14)
```

**Comment by Andreyco** [comment]
Use [this npm module](https://www.npmjs.com/package/object-assign), or inluce [this polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill)

**Comment by binarykitchen** [comment]
thanks man, `require('polyfills')` at the top did it for me
