### ISSUE TITLE
Error: Invariant Violation: FixedDataTable.getInitialState(): must return an object or null

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#122]
When using this very simple coffee code without children for a Jest test

```
<FixedDataTable.Table
  width     = 100
  height    = 1000
  rowsCount = 10
  rowHeight = 10
  rowGetter = {->}
>
</FixedDataTable.Table>
```

I get the above error.

**Comment by ehzhang** [comment]
Hey! I whipped up a JSBin to test, and this doesn't seem to be an error for React 0.13 + FixedDataTable v0.3.0

http://jsbin.com/wirubo/1/edit?html,js,output
