### ISSUE TITLE
IE9 scrollbar issue

### ISSUE THREAD

**Issue by llh1** [facebook/fixed-data-table#127]
Hi everybody,

I've found an issue specific to IE9 (well it may be also present in IE10, I haven't tried), when scrolling to the end of the table. It can be reproduced with the example here http://facebook.github.io/fixed-data-table/example-object-data.html. If your window takes all the place in your screen, that's mostly fine (sometimes fail though), but try to change the height of you IE9 window, refresh and scroll to the bottom of the page, you'll see some blank space, which prevent to see the data. And the scrollbar moves back to the top everytime.

It looks like it's related to the height of the browser window, but I cannot find the reason. Anybody has an idea about it? If you cannot reproduce it, I can make a gif to show the behaviour, let me know.

Thanks

**Comment by llh1** [comment]
Hi all,

I think I've found the issue with IE9. I'll send a pull request a little bit later. 
It happens in the function ```PrefixIntervalTree```. At some point, it needs to initialize the Int32Array with this line: ```var Int32Array = global.Int32Array || Array;```

The problem is IE9 doesn't have Int32Array, so it falls back to Array. 
Next line: ```this.$PrefixIntervalTree_value = new Int32Array(nodeCount);```. On IE9, when you create array like this, it initializes everything to ```undefined```, but it should be initialized to 0 to work fine.

**Comment by pieterv** [comment]
Nice find! Would love a PR for this :)
