### ISSUE TITLE
So... where are the tests?

### ISSUE THREAD

**Issue by moimikey** [facebook/fixed-data-table#130]
Just starting to notice that there aren't any. How can you live?!

**Comment by pieterv** [comment]
So we have unit tests setup for this code in the FB code base which we run when we sync code changes back in to FB we just haven't had the time to pull them out and setup the infra in this repo. I agree this is pretty bad though :(, ill try setting this up before the next release.

**Comment by moimikey** [comment]
I couldn't _really_ believe this would be testless. good to know, thanks!

**Comment by jketcham** [comment]
Also looking forward to tests!

**Comment by MadebyAe** [comment]
Seriously?

**Comment by codemaster220** [comment]
@pieterv - How soon can we have the unit test for it?

**Comment by jainprash** [comment]
Looking forward for the test suite sooner.....

**Comment by jtrussell** [comment]
Hi - it's been a while since there was an update here. I'd like to consider this component for an upcoming project but I can't really recommend it without tests present. Is this something that's still coming? It's essentially a blocker for us on using or contributing to the component.

**Comment by KamranAsif** [comment]
@jtrussell Hey,

This library hasn't been updated for a while. We've been trying to maintain a fork https://github.com/schrodinger/fixed-data-table-2 that includes unit test as well as bug fixes and new features.

We are slowly building up the tests and would love help from the community

**Comment by wcjordan** [comment]
@zpao is there anyway you could sync the existing tests Pieter mentioned onto a branch for us?  We'd be interested in integrating them into FDT2 if possible.
