### ISSUE TITLE
Render HTML in Table Cell With 'dangerouslySetInnerHTML' Prop

### ISSUE THREAD

**Issue by ConAntonakos** [facebook/fixed-data-table#132]
Is there a way to render HTML within a table's cell or a column of cells with the prop, `dangerouslySetInnerHTML`?

**Comment by ConAntonakos** [comment]
I might have spoken early. This should perhaps solve my question?: https://github.com/facebook/fixed-data-table/blob/0fdacd8ef17b45d2b8210a267fb19d5360499bff/site/examples/ObjectDataExample.js

**Comment by pieterv** [comment]
Yeah you will just want to setup a custom `cellRenderer` on the column which you can then render what ever you want with react :)

**Comment by ConAntonakos** [comment]
Thanks, @pieterv. I do not know why I'm struggling with this, but I setup a custom cellRenderer function like so:
```
function renderLink(cellData){
  return React.DOM.div({ dangerouslySetInnerHTML: {__html: cellData} });
}
```
Unfortunately, I keep getting this error: `Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined` from the `checkAndWarnForMutatedProps` function, line # 10476.

**Comment by airwin** [comment]
I think if use custom cellRenderer, you can return anything without using the `dangerouslySetInnerHTML`, maybe just `return <div>{cellData}</div>`?

**Comment by ConAntonakos** [comment]
Thanks for your response, @airwin. Unfortunately, that didn't work either. I actually even used the `<ExampleImage />` React component, and I am still getting the same error. :(

**Comment by pieterv** [comment]
@ConAntonakos I think in the latest React you would write it like this if your not using JSX:
```
function renderLink(cellData){
  return React.createElement('div', { dangerouslySetInnerHTML: {__html: cellData} });
}
```
Does that work?

**Comment by rundis** [comment]
I struggled bigtime with this as well. By coincidence I found that it worked when using the minified version of react 0.13.3, but got the `Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined` when using the development (non-minified) version.
