### ISSUE TITLE
Children are passed without a component type.

### ISSUE THREAD

**Issue by SupremeTechnopriest** [facebook/fixed-data-table#136]
There are some checks in `FixedDataTable.react.js:657` that are looking for a `type` field that is not defined.  I tried to track down the problem, but can't figure out why React isn't giving these children types.

This causes ColumnGroup to fail.

**Comment by ehzhang** [comment]
Hi! Can you explain a little bit more about what you mean here?

**Comment by SupremeTechnopriest** [comment]
It seems ComponentClass.type has been deprecated in React 0.13.  I was also forgetting to set a column group height.  I have it working now so I will close this.  Thank you
