### ISSUE TITLE
Features for v0.3.0

### ISSUE THREAD

**Issue by pieterv** [facebook/fixed-data-table#143]
We plan to implement following improvements for v0.3.0 (the next release).

- [x] Only render visible columns #49
- [x] Implement groupHeaderRenderer #41

**Comment by cosminnicula** [comment]
Can you also add #129 Keyboard / Screen-Reader Accessibility to this? :) Thanks!

**Comment by lambdaburrito** [comment]
Lazy loading / Infinite Scrolling would be great.

**Comment by nidu** [comment]
Do you plan to add row grouping?

**Comment by wlis** [comment]
v 0.3.0 has been released. I'll update changelog soon.
@nidu At some point in the future row grouping should be possible to achieve, but we don't have timeline for these changes yet.

**Comment by cesarandreu** [comment]
Cool! Thanks :D.
