### ISSUE TITLE
headerRenderer returning a ReactElement is broken in latest version

### ISSUE THREAD

**Issue by nbostrom** [facebook/fixed-data-table#146]
Here's an updated version of your sorting example using latest react and fixed-data-table:
http://jsbin.com/wukiwekozu/3/edit

This throws an error and breaks. If you change the _renderHeader method to return the label directly it works without errors.

Bumped into this trying to implement sorting.

**Comment by nbostrom** [comment]
This happens when React checks for mutated props so this only happens when using the development build of React.

**Comment by ehzhang** [comment]
Hi @nbostrom !

This appears to be working with react v0.13 and fixed-data-table v0.3.0. This example uses both most recent react and fixed-data-table versions.

http://jsbin.com/pukiri/6/edit?html,js,output

The example is also up on the main site, https://facebook.github.io/example-sort.html

**Comment by nbostrom** [comment]
Works like a charm! Thanks!
