### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by cesarandreu** [facebook/fixed-data-table#148]
Having a `CHANGELOG.md` lets users see at a glance what stuff could've changed. Not hugely critical, but it's something very nice to have. 

From #105 it looks like the following were released with `0.2.0`?

* Don't absorb the wheel event if scroll is at the end of range #33 #84
* Investigate weird errors with React 0.13 #104 #83
* Fix vertical positioning errors and pixels bleeding through 1px gaps
* Improve Firefox perf #5
* Use Babel for transform (remove the need for global polyfills, Object.assign) #102
* Add UMD support to dist build #103
* Make footer stay on the bottom when using Height prop #97
* Unify footer data API with header/groupHeader data API

**Comment by pieterv** [comment]
Hey @cesarandreu thanks for bringing this up! I have put this info into the github release :) https://github.com/facebook/fixed-data-table/releases/tag/v0.2.0 And we will continue to do this for all future releases.
