### ISSUE TITLE
Features for v 0.4.0

### ISSUE THREAD

**Issue by wlis** [facebook/fixed-data-table#155]
We plan to include following features in v 0.4.0
- [ ] Create new API for rendering cells using react components instead of cellRenderers
- [x] Split layout and theme styles #121

**Comment by TomClarkson** [comment]
Can't wait for this :)

**Comment by cosminnicula** [comment]
+1

**Comment by cesarandreu** [comment]
No plans for implementing #49? :(

**Comment by wlis** [comment]
@cesarandreu We have solved part of it with 0.3.0 release ( #156 ). You can now mark your columns using allowCellsRecycling prop and this will allow table to get not render cells in these columns when they are outside of viewport. 
This doesn't allow table to has any number of columns, but we tested on 1000 columns and it works quite well. There will be additional example coming soon.

**Comment by cesarandreu** [comment]
Oh cool, I'll try it out, thanks :D.

**Comment by cosminnicula** [comment]
Any chance to see #129 Keyboard / Screen-Reader Accessibility in this release?

**Comment by cosminnicula** [comment]
Guys, any news on accessibility? I was wondering if there are any plans to have it in the near future.

**Comment by ehzhang** [comment]
Version v0.4.0 has been released with bugfixes and splitting layout and theme styles.

**Comment by ehzhang** [comment]
Please see #193 !

**Comment by cosminnicula** [comment]
Great work! Thanks!
