### ISSUE TITLE
isResizable={true} throws errors ?

### ISSUE THREAD

**Issue by Reggino** [facebook/fixed-data-table#164]
Hi guys,

First of all: awesome stuff :-) Thanks.

Using ```react@0.13.3``` and ```fixed-data-table@0.2.0``` i get an error when using ```Col.isResizable``` after dragging the column border on Chrome 43.0.2357.81 on Ubuntu 15.04 64bit:

```
Uncaught TypeError: this.props.onColumnResizeEnd is not a function_onColumnResizeEnd 
@ FixedDataTableColumnResizeHandle.react.js:153_onMouseUp 
@ DOMMouseMoveTracker.js:152
```

Am i missing something here?

**Comment by wlis** [comment]
Did you specify the onColumnResizeEnd prop in the table? The table doesn't actually resize columns, it just provides UI. The onColumnResizeEnd will get info about updated column size and ultimately you will have to render the table with updated columns.

**Comment by Reggino** [comment]
Ah thanks for that. Maybe the docs could point out that ```onColumnResizeEndCallback``` is required for the Table whenever a Column has ``` isResizable ``` set to true...

**Comment by ehzhang** [comment]
Indeed, the documentation isn't really clear about this: it'll be added soon. Thanks!

**Comment by muraveill** [comment]
Hi,
Sorry but I don't get it. Your Resizable columns example* has no mention of 'onColumnResizeEnd' in its code, only a 'onColumnResizeEndCallback'. When I use the latter, more or less copying your example, I get the same error message as above: `this.props.onColumnResizeEnd is not a function`.

*http://facebook.github.io/fixed-data-table/example-resize.html

**Comment by ehzhang** [comment]
@muraveill, please use the `onColumnResizeEndCallback.` wlis was abbreviating the prop name.

**Comment by delafont** [comment]
I do use that prop, and define it, yet it throws `this.props.onColumnResizeEnd is not a function`. I copied the function and the prop line from the example (except the forceUpdate()).
```
_onColumnResizeEndCallback: function(newColumnWidth, dataKey) {
    columnWidths[dataKey] = newColumnWidth;
    isColumnResizing = false;
    this._onDataChange();
},
```
then
`<Column ... onColumnResizeEndCallback={this._onColumnResizeEndCallback} ...  />`
and it throws.
Is it the propTypes, or the onContentHeightChange, or something else that I am missing ?

**Comment by ehzhang** [comment]
@delafont - you'll want to use the `onColumnResizeEndCallback` on the Table, as it is a Table property.

You can see the documentation here: http://facebook.github.io/fixed-data-table/api-table.html

It is admittedly a little confusing, but the callback doesn't run on a single column but watches for any resize event on all columns, so it exists at the table level.

**Comment by delafont** [comment]
I see. Thank you ! I would have tried for days before noticing that.

**Comment by ehzhang** [comment]
No problem :)

I'm going to close this issue since the documentation has been updated with this information. If still unclear, feel free to reopen!

**Comment by pramodrhegde** [comment]
`<Table ref="entriesTable"
							   rowsCount={this.props.entries.length}
							   width={this.state.tableWidth}
							   height={this.state.tableHeight}
							   headerHeight={30}
							   rowHeight={30}
							   rowGetter={this._getEntry.bind(this)}
							   onColumnResizeEndCallback={this._onColumnResized}
							   isColumnResizing={this.state.isColumnResizing}>
							<Column 
								width={this.state.columnWidths.url} 
								dataKey="url" 
								isResizable={true}
								label="Url" 
								flexGrow={null}/>
							<Column 
								width={this.state.columnWidths.size} 
								dataKey="size" 
								isResizable={true}
								label="Size" />
							<Column 
								width={this.state.columnWidths.time} 
								minWidth={200} 
								dataKey="time" 
								isResizable={true}
								label="Timeline" />
						</Table>`
`_onColumnResized(newColumnWidth,dataKey){
		var columnWidths = this.state.columnWidths;
		columnWidths[dataKey] = newColumnWidth;

		this.setState({
			columnWidths:columnWidths,
			isColumnResizing:false
		});
	}`
`constructor(){

		super();

		this.state={
			columnWidths:{
				url:500,
				size:100,
				time:200
			},
			tableWidth:1000,
			tableHeight:500,
			isColumnResizing:false
		};

		this._onColumnResizeEndCallback = this._onColumnResized.bind(this)
	}
`

Hi guys above is my code eveerything seems proper still i am getting same exception anything that i am missing?
