### ISSUE TITLE
Changelog for v0.3.0 is missing

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#166]
When I update from v0.2.0 to v0.3.0 then my code does not work anymore. Hence my guess that breaking changes have been introduced but without seeing a changelog, I have reverted to v0.2.0 for now.

(And according to sem-versioning, I think it should have been version 3.0 instead. Because there are breaking changes.)

**Comment by cesarandreu** [comment]
@binarykitchen:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

[source](http://semver.org/)


+1 to changelog though :D

**Comment by wlis** [comment]
Thank you for pointing this out. We will add changelog for 0.3.0 soon.

**Comment by binarykitchen** [comment]
@cesarandreu re: initial development vs versioning, i disagree, based on this comment https://github.com/dominictarr/semver-ftw/issues/2#issuecomment-13874220

firstly, we already use this fixed-data-table package in production, so it's not just an experiment. it's already serious. secondly, anytime you introduce breaking changes, the major version shall be incremented, no matter what. this to reflect the breakage.

**Comment by ehzhang** [comment]
@binarykitchen a changelog for version v0.3.0 has been added - most notably, support for React 0.12 has been discontinued.

You can find it here: https://github.com/facebook/fixed-data-table/releases

**Comment by binarykitchen** [comment]
thx, looking good
