### ISSUE TITLE
using react component as cell

### ISSUE THREAD

**Issue by bsr203** [facebook/fixed-data-table#169]
I am trying to render dropdown (react-select) on fixed-data-table, and met with some issue. Please see the details here http://stackoverflow.com/questions/30675743/positioning-a-select-component-within-data-table-reactjs-component

Has anyone managed to do something similar, or any help on how I could make progress on this?

I will close this issue as soon as I get some feedback on this. thanks a ton.

**Comment by ehzhang** [comment]
Hi!

I looked into this, and created this JSBin to play around with adding this select box.
http://jsbin.com/ladiko/1/edit?html,js,output

Unfortunately, this appears to be a compatibility issue with the react-select component and react-table's CSS, but a default HTML <select> works fine.

Let me know if you have any questions, or would like me to prod deeper :)

Cheers,
Edwin

**Comment by bsr203** [comment]
Thanks a ton for helping me with this. I tested with some other components which add drop downs dynamically and met with same issue. I wish it works, but understand not a core requirement for data table. Closing now. thanks again.

**Comment by kevinhaas** [comment]
I was able to circumvent this by giving the parent container 'z-index: -1;'. Haven't noticed any strange behavior yet, but this will always keep the table on the bottom, which works fine for me.
