### ISSUE TITLE
Adding onRowMouseLeave

### ISSUE THREAD

**Issue by mjibson** [facebook/fixed-data-table#17]
Does it make sense to add onRowMouseLeave to the Table API? onRowMouseEnter is great, but I want to have a feature where the row changes when the mouse is over it, then reverts back when it leaves. Doing this with just :hover CSS properties might work, but I'm wondering if a JS handler is better.

**Comment by Daniel15** [comment]
If you're only styling it then I'd suggest using CSS :hover rather than JS.

**Comment by pieterv** [comment]
@mjibson Yes i think this makes sense, we also have `onRowMouseDown` but not up. You can probably use CSS to get around this for now but there are certainly use cases which warrant having enter and leave.

cc @wlis, @jbonta any reason why we wouldn't want to add these?

**Comment by jmorrell** [comment]
You would also need mouse hooks in lieu of `:hover' in CSS if you were wanting inline all of your CSS in javascript.

In either case, this could result in bad performance while scrolling, so it might be discouraged somewhere? If this is a concern we could give a warning and a link to description of how to disable hover styles on scroll? Perhaps we could add a class to the table during scroll to help them? E.g. `:not(.is-scrolling) fixedDataTableRow:hover`. Or if we rely on javascript, we could just not fire those callbacks during scrolling.

**Comment by Daniel15** [comment]
I think it makes sense to add `onRowMouseLeave` to the API, but I wouldn't use it for styling. You should try to not re-render while scrolling as this will seriously hurt performance. CSS :hover should be fine, but adding and removing class names on the React component will force it to constantly re-render rows while scrolling. In general you should avoid heavy operations like that while scrolling.

**Comment by wlis** [comment]
@pieterv There is no reason not to add onRowMouseLeave to the API. It is not there because we never needed it.
