### ISSUE TITLE
cellClassName is assigned to the column's header

### ISSUE THREAD

**Issue by Martynas-P** [facebook/fixed-data-table#171]
When I use cellClassName property to assign a class to a cell, it also assigns the class to the Column Header (but not the Column Group Header), when the documentation says that the class should be applied to the data cells only.

I'm using React 0.13.3 with Fixed Data Table 0.3.0

Code which reproduces the bug is at https://gist.github.com/Martynas-P/c50a5905a3cdd430a40c

![image](https://cloud.githubusercontent.com/assets/2590908/8093613/04863396-0fba-11e5-952e-dbeee2a79231.png)

**Comment by ehzhang** [comment]
Hey @Martynas-P !

Thanks for bringing up this bug! Indeed, this doesn't seem to be the expected behavior. I'll look into a fix.

cc @pieterv

**Comment by ehzhang** [comment]
This bug has been fixed in v0.4.0. Thanks!
