### ISSUE TITLE
Table does not render correctly using material UI + fixed-data-table

### ISSUE THREAD

**Issue by kenr** [facebook/fixed-data-table#174]
I'm using:

|Module|Version|
|--------------------|----------|
| React               | 0.13.3 |
| material-ui        | 0.9.1   |
| fixed-data-table| 0.3.0   |
| browserify        |10.2.4 (to generate bundle.js)|
| babel| 6.1.2|

When rendering the table the columns are written on top of each other:

![image](https://cloud.githubusercontent.com/assets/64542/8225870/b88b9be4-1599-11e5-8f25-02aa1b3b55ab.png)

I'm not sure if this is a browserify issue since it seems like the CSS  for fixed-data-table is not applied. The CSS definitions exists in the bundle.js file though. 

Extract from gulpfile.js

``` javascript
gulp.task('build', function () {
  browserify({
    entries: 'app/app.jsx',
    extensions: ['.jsx'],
    debug: true
  })
  .transform(babelify.configure({
        optional: ["es7.classProperties"]
      }))
  .bundle()
  .on('error', swallowError)
  .pipe(source('bundle.js'))
  .pipe(gulp.dest('dist'));
});
```

Extract from app.jsx

```
<Paper>
    <Table
        rowHeight={10}
        rowGetter={entriesGetter}
        rowsCount={entriesSize()}
        width={500}
        height={500}
        headerHeight={20}
        overflowX={"auto"}
        overflowY={"auto"}
    >
        <Column
            label="Timestamp"
            width={100}
            dataKey="timestamp"
            />
        <Column
            label="Severity"
            width={100}
            dataKey="severity"
            />
        <Column
            label="Message"
            width={200}
            dataKey="message"
            />
        </Table>
</Paper>
```

**Comment by ehzhang** [comment]
Hmm! We haven't tested this with material UI - have you tried including the fixed-data-table.css file manually?

**Comment by kenr** [comment]
Your suggestion does the trick, thank you. Added 
````HTML
<link href="fixed-data-table.css" rel='stylesheet' type='text/css'>
```
and now the table is correctly formatted. 

Is this an issue with browserify in combination with fixed-data-table then ? Is browserify supported by fixed-data-table ?

**Comment by ehzhang** [comment]
Glad to hear it's all fixed @kenr ! 

Fixed-data-table relies on including the css in order to render properly, regardless of the method you use to bundle and/or transpile the jsx of javascript - in this case, browserify.

**Comment by skosch** [comment]
Just ran into the same problem – for those of you using a module loader of some sort, you can `require` or `import` the file `fixed-data-table/dist/fixed-data-table.css` to get it to work.

**Comment by TiagoGouvea** [comment]
import 'fixed-data-table/dist/fixed-data-table.css';

**Comment by ahmedtabrez** [comment]
There is [this package](https://github.com/andela-cdaniel/mui-data-table) written by a folk. You might be interested. I haven't tried it and I don't know if it's still maintained.
