### ISSUE TITLE
:bug scroll bar is not updating its position in examples when scrolling

### ISSUE THREAD

**Issue by skmasq** [facebook/fixed-data-table#177]
In following examples scroll bar does not update its position when using mouse-wheel or touch pad: "With JSON Data", "Fluid column widths", "Resizable columns", "Column Groups".

Browser: Chrome Version 43.0.2357.124 m

**Comment by ehzhang** [comment]
Hi! Thanks for bringing this up. The examples on the site will be working again soon, there has just been a small hiccup with a recent commit.

**Comment by ehzhang** [comment]
@skmasq things should be working again. The site publishing script happened to pick up a few of my local changes by accident, sorry about that!

**Comment by skmasq** [comment]
@ehzhang  Thank you, cheers!
