### ISSUE TITLE
Add a download for people that don't use NPM

### ISSUE THREAD

**Issue by Daniel15** [facebook/fixed-data-table#18]
Not everyone uses NPM, the site should have a regular JavaScript file download. It should use UMD for the module.

**Comment by pieterv** [comment]
I guess we just need to add a link in the README to the dist files. For UMD support we just need to add a flag in the `webpack.conf.js`.

**Comment by Daniel15** [comment]
Oh cool, I didn't even notice the dist files. It would be cool to get them onto either CDNJS or the Facebook CDN too so people can just hotlink them if they want to :)

**Comment by pieterv** [comment]
Yes a CDN would be sweet, im not sure how to do that. Im curious is there any advantage over using rawgit.com?

**Comment by Daniel15** [comment]
Well, ideally built assets should never be in source control, only the source files :). A `dist` directory in source control results in lots of noise in every diff, and quickly becomes out of date once someone forgets to update it. 

Loading directly from a Git repo is unversioned. I guess you could use tags, but a proper CDN will have better performance. I believe it's fairly simple to add new libraries to CDNJS.

**Comment by pieterv** [comment]
I have added UMD support and versioned build files are available via https://github.com/facebook/fixed-data-table/releases. I will create a specific issue for adding files to the CDN.
