### ISSUE TITLE
Addition of columns dynamically, is there a good way to achieve this?

### ISSUE THREAD

**Issue by sharky93** [facebook/fixed-data-table#187]
Is it beyond the use case for which Fixed-Data-Table was built?, again an API for that would be great.

**Comment by ehzhang** [comment]
Yes, this is beyond the scope of FixedDataTable. You can provide your own `Column`s as a child of the `Table` component. When the columns you provide are changed, the table will update accordingly.

Here's a simple example:
http://jsbin.com/putuzi/4/edit?html,js,output

**Comment by ehzhang** [comment]
I'm going to be closing this issue as mentioned above, as adding an API for column addition is beyond the scope of this table.
