### ISSUE TITLE
Use native scrolling when available.

### ISSUE THREAD

**Issue by Andreyco** [facebook/fixed-data-table#196]
Investigate how would native scrolling behave when "overlay" scrollbars are available in system/browser. 
FDT would not generate scrollbars in this case.

**Pros:** performance
**Cons:** don't know. Is it even possible with current impementation?

**Comment by ehzhang** [comment]
Hey @Andreyco! The way that fixed-data-table is actually able to work is because we take over native scrolling and replace it with our own scrollbar. That's currently how we're able to achieve the performance that we do.
