### ISSUE TITLE
Chrome find bar undesirable behavior

### ISSUE THREAD

**Issue by krystian-3c** [facebook/fixed-data-table#201]
When you use browser find bar (ctrl+f) on chrome to search something which is hidden by horizontal scroll you end up with badly scrolled containing row. 

Anyone have an idea how to avoid this undesirable behavior?
![01](https://cloud.githubusercontent.com/assets/12048630/8644565/5ebc135e-2940-11e5-9812-31b9474336ee.png)

**Comment by ehzhang** [comment]
Hi! This is a known bug (see #149). I'm going to close this issue in favor of the previous - but unfortunately, we cannot currently prevent this behavior because of the way we manage scrolling.
