### ISSUE TITLE
Scrollbar obstructs content

### ISSUE THREAD

**Issue by rmilesson** [facebook/fixed-data-table#204]
The scrollbar currently obstructs content in a table.
We've been dealing with this issue by creating an empty column or making sure we've got no right-aligned content in the last column. But sometimes that just isn't possible. I've attached a screenshot showing the problem in one of our columns displaying a DateTime.

![scrollbar-above-content](https://cloud.githubusercontent.com/assets/1110411/8722662/31798f78-2bc7-11e5-8eb3-45f81da7a833.png)

**Comment by ehzhang** [comment]
Hi @rmilesson! Can you elaborate on what you mean by 'not possible'?

This current behavior is currently one that we expect - perhaps you might be interested in having something like a CSS rule that sets the opacity of the scrollbar to 0, but brings it back up on hover? You can customize the Scrollbar's CSS in the `fixed-data-table-style.css` file, or by adding your own CSS.

**Comment by ehzhang** [comment]
I'm closing this because there hasn't been any update, and a solution exists. Feel free to reopen if this persists!
