### ISSUE TITLE
ability to add margin to the left and right of rows

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/fixed-data-table#211]
As the width of a row is hardcoded I can't think of a way to add a margin to the left and right of a row in css or otherwise. Basically what I want is if a table is wider than its container, when you scroll it to the left when you reach the end there will be a margin between the edge of the container and the last cell of the table.

This might be possible now but I'm just missing it...

**Comment by ehzhang** [comment]
Have you tried adding padding to the parent container?

Otherwise, could you explain this in greater detail or provide a screenshot? I'm a bit confused as to what you mean here, visually :S

**Comment by chrisdrackett** [comment]
so hopefully the following helps:

![example](http://cl.ly/image/2w370b1u1m2e/Screen%20Shot%202015-07-21%20at%204.09.51%20PM.png)

basically the first image is when you are scrolled all the way left, the second all the way right. The margin is within the table, not on the wrapper.

**Comment by ehzhang** [comment]
Sorry, I'm still confused - is this the behavior you currently have, or the one you're trying to achieve?

**Comment by chrisdrackett** [comment]
this is what I'm trying to achieve, I'm not sure if its possible with the current code

**Comment by ehzhang** [comment]
@chrisdrackett thanks for clarifying - I've been able to solve this in JSBin.
http://jsbin.com/cafeza/edit?html,css,js,output

This isn't a problem with FixedDataTable, but the way it appears you're using `overflow: auto` or `overflow: scroll`. Read here: http://stackoverflow.com/questions/11695354/css-right-margin-does-not-work-inside-a-div-with-overflow-scroll

Basically, you'll want to apply the `display: inline-block` rule to the table, or its wrapper.

**Comment by chrisdrackett** [comment]
I'm trying to achieve the same, but without the extra scrollbar. Now you have a scrollbar on the table and the wrapper, which isn't a great user experience.

**Comment by ehzhang** [comment]
If you need to remove the scroll bar in the table, you can feel free to make it non visible with CSS, or by making the overall table width the sum of the widths of the table columns so that the table itself doesn't scroll.

With regards to user experience, this concept of a scrolling table within a scrollable wrapper is already not a great experience, scroll bar or not.

**Comment by chrisdrackett** [comment]
I'm just going to solve this by adding two extra empty columns at the beginning and end of my table. I can then use some CSS to render these new columns as transparent and "fake" the edge of the table on the adjacent columns.
