### ISSUE TITLE
Column not resizing when used with cellDataGetter

### ISSUE THREAD

**Issue by pavanpodila** [facebook/fixed-data-table#217]
For this configuration, resizing does not work:

``` xml
                <Column dataKey="request.url"
                        cellDataGetter={this._readKey}
                        width={this.state.columnWidths.url}
                        label="Url"
                        isResizable={true} />

```

**Comment by ehzhang** [comment]
To help debug - have you defined your `onColumnResizeEndCallback`, and if so, can you include that code too? 

Thanks :)

**Comment by pavanpodila** [comment]
Ya, I've it like so:

``` js
    _onColumnResized(newColumnWidth, dataKey) {

        var columnWidths = this.state.columnWidths;
        columnWidths[dataKey] = newColumnWidth;

        this.setState({columnWidths: columnWidths, isColumnResizing: false});
    }

```

``` xml
            <Table rowsCount={this.props.entries.length}
                   width={this.state.tableWidth}
                   headerHeight={30}
                   height={500}
                   rowHeight={30}
                   rowGetter={this._getEntry.bind(this)}
                   isColumnResizing={this.state.isColumnResizing}
                   onColumnResizeEndCallback={this._onColumnResized.bind(this)}>

```

**Comment by ehzhang** [comment]
Hey @pavanpodila , I have not been able to reproduce this bug - I wrote up an example on usage here, attempting to mimic what you're doing. You should also remove the `.bind` calls on your `rowGetter` and `onColumnResizeEndCallback` functions, since React component methods may only be bound to the component instance.

http://jsbin.com/safipo/2/edit?html,js,console,output

Unless this can be reproduced, I'll close this issue - but I'll leave it open for now while some debugging happens!

**Comment by ehzhang** [comment]
Actually, it looks like what you're getting as a `dataKey` is not the same way you represent your columnWidths. You set your Column's dataKey as `"request.url"`, so when you get the dataKey back form the column resize callback, you're receiving `"request.url"`, not `.url` as you expect in your Column width.

You'll likely need to change that line to `this.state.tableWidths['request.url']`.

Let me know if that solved your problem!

**Comment by pavanpodila** [comment]
Hi Edwin,
         Good catch. The dataKey was the problem. BTW, I am using `bind` because of ES6. Looks like React does not autobind methods when used via ES6. 

Thanks a lot for taking time to help :-)
