### ISSUE TITLE
Allow react 0.14.0-beta1?

### ISSUE THREAD

**Issue by cesarandreu** [facebook/fixed-data-table#219]
If it works with it, that is :D.

**Comment by grydstedt** [comment]
+1

**Comment by ts-smith** [comment]
This

**Comment by pieterv** [comment]
FixedDataTable will definitely work with the beta since FB runs React master internally. But last time i tried to do this i couldn't get the npm dependencies to allow a beta as well as the normal versions. If anyones has an idea how the npm dependency versioning should look for this i will be happy to do the release.

**Comment by cesarandreu** [comment]
That's great to hear @pieterv! As a work-around I've just been vendoring or using forked versions, but it's far from ideal :(.

Based on [this issue's discussion](https://github.com/facebook/react/issues/4542), it looks like you could set the dependency to:

```json
{
  "peerDependencies": {
    "react": ">=0.13.0 || ^0.14.0-alpha"
  }
}
```

Looking at libs in the wild, react-dnd's package.json has:

```json
{
  "peerDependencies": {
    "react": ">=0.13.0 <0.15.0 || 0.14.0-beta1"
  }
}
```

However, (I think?) that won't work with newer 0.14 releases. (e.g. 0.14.0-beta3)

Another lib, react-redux, [apparently](https://github.com/gaearon/react-redux/pull/4) just straight-up removed the peer dependency.

**Comment by ehzhang** [comment]
So as to keep with the latest releases with react, we've added support for React v0.14.0-beta3 with v0.4.6 (but not beta1 or beta2).

**Comment by pieterv** [comment]
@cesarandreu thanks for the info! Let us know if the release doesn't solve the problem for you.
