### ISSUE TITLE
How can I get the row to highlight when hovering over a row

### ISSUE THREAD

**Issue by elanbar** [facebook/fixed-data-table#222]
I am able to successfully set the background color when hovering over a cell, using the following CSS:

    .public_fixedDataTableCell_main:hover {
      background-color: yellow;
    }

However, I am unsuccessful in making this work for the whole row. I have tried the following:

    .fixedDataTableRowLayout_rowWrapper:hover {
      background-color: yellow;
    }

The above works on setting the font style and weight, but not the background color. I have tried the same on various CSS classes: 

    public_fixedDataTableRow_main
    fixedDataTableRowLayout_main
    fixedDataTableRowLayout_rowWrapper
    public_fixedDataTable_bodyRow

I have also tried adding `!important` and in doing this I saw a brief flash of the background color, but it gets replaced/lost.

**Comment by bumxnhoc** [comment]
.public_fixedDataTableCell_main:hover {
  background-color: yellow;
}

**Comment by elanbar** [comment]
That is what I wrote which works for me for a hover highlight on a cell. What I am looking for is how to get the whole row to highlight. The row hover highlight is not working for me.

**Comment by dearrrfish** [comment]
this is solution:
```
.fixedDataTableRowLayout_rowWrapper:hover .public_fixedDataTableCell_main {
  background-color: yellow;
}
```

**Comment by elanbar** [comment]
And that works! Thank you!

**Comment by donnrri** [comment]
I have no idea how you worked that out but I am very glad you did. Many thanks !  By the way to stop the header highlighting

 .public_fixedDataTable_header:hover .public_fixedDataTableCell_main {

    background-color: #FFFFFF;
}
 but you probably got that

**Comment by BracWebb** [comment]
Actually, using `fixedDataTableRowLayout_rowWrapper` is not ideal as you should use the `public_` prefixed classnames. Also, as donnrri pointed out, this causes the header to highlight. These are the solutions you are looking for:

Hover and highlight header and body rows:
```
.public_fixedDataTableRow_main:hover .public_fixedDataTableCell_main {
  background-color: yellow;
}
```

Hover and highlight only the header:
```
.public_fixedDataTable_header:hover .public_fixedDataTableCell_main {
  background-color: yellow;
}
```

Hover and highlight only the body rows:
```
.public_fixedDataTable_bodyRow:hover .public_fixedDataTableCell_main {
  background-color: yellow;
}
```

Hover and highlight only the body rows, different for even and odd:
```
.public_fixedDataTableRow_even:hover .public_fixedDataTableCell_main {
  background-color: yellow;
}
.public_fixedDataTableRow_odd:hover .public_fixedDataTableCell_main {
  background-color: green;
}
```

**Comment by bavicj** [comment]
Hi, your solution does not work with fixed columns. Row gets highlighted, but when you scroll horizontally, cells of highlighted row do not 'hide' behind fixed columns, but remains visible (see screenshot)
<img width="353" alt="screen shot 2017-03-21 at 15 51 19" src="https://cloud.githubusercontent.com/assets/3510699/24153306/4fde11d0-0e4e-11e7-9a2e-a3f5032a5a30.png">
