### ISSUE TITLE
Optimisation of BufferedRows

### ISSUE THREAD

**Issue by khankuan** [facebook/fixed-data-table#229]
Hey, I saw that the BufferedRows shouldComponentUpdate always returns true and PureRenderMixin should not be used. Is there a reason why?

Thanks ;)

**Comment by ehzhang** [comment]
Adding PureRenderMixin means it will never update - if you try it, the table just sits there completely stationary :p

**Comment by khankuan** [comment]
Ah ic, are there any ways to optimise a single row not to update, such as when the data is really the same.

**Comment by ehzhang** [comment]
That is actually how the table works right now! The rerender of s cell is determined by the results of the rowGetter or the cellDataGetter. When that changes, a render is triggered.

**Comment by ehzhang** [comment]
@khankuan are you experiencing poor performance? It'd be great to see if its something that we should address.

**Comment by khankuan** [comment]
Ah nope, was just thinking if i could make my application even faster :P But the current one works great and scales. (Y)

**Comment by ehzhang** [comment]
Great to hear it! If you don't mind I'm going to close this issue then - feel free to open it if anything changes.

**Comment by khankuan** [comment]
@ehzhang hmm seems the lag does occur. Basically I'm using rowEnter and rowLeave to set a border bottom to the row, by setting a state and customising handleRowClassName.
