### ISSUE TITLE
Use browser window scrollbar instead of container scrollbar

### ISSUE THREAD

**Issue by alolis** [facebook/fixed-data-table#232]
Hello,

I am wondering if it's possible to use the main browser window scrollbar instead of using the container scrollbar.

Thank you for your time

**Comment by ehzhang** [comment]
Hi @alolis! Because manage our own scrolling for performance, we don't use the native scrollbar.

**Comment by alolis** [comment]
@ehzhang Ah damn :( Thanks for your reply though!
