### ISSUE TITLE
Replace dependency on cloneWithProps with React.cloneElement

### ISSUE THREAD

**Issue by bolinfest** [facebook/fixed-data-table#233]
Currently, this package contains the following code:

    require('react/lib/cloneWithProps')

This does not play well when using [react-for-atom](https://www.npmjs.com/package/react-for-atom) instead of `'react'`. If the uses of `cloneWithProps()` were replaced with `React.cloneElement()`, it would make things easier to use this from Atom. Ideally, we would then be able to eliminate https://github.com/facebooknuclideapm/fixed-data-table-for-atom.

**Comment by bolinfest** [comment]
Here is our current workaround, which isn't so great: https://github.com/facebooknuclideapm/fixed-data-table-for-atom/commit/dbac0afcc42feb13a8cc6e0d4010e7d75bbe7ee5.

**Comment by ehzhang** [comment]
cloneWithProps has been removed in version v0.4.2! :)
