### ISSUE TITLE
Table Header Column separate component problem

### ISSUE THREAD

**Issue by fullvlad** [facebook/fixed-data-table#234]
Hi everyone!
I want to render a table with many columns (around 60) and I'd like to be able separate all the logic for Header columns and sorting in a different React module. This is what I've done:

```
 <Table  ..... >
    <ColHeader type='id' />                   
 </Table>

// separate file
ColHeader = React.createClass({
    render() {
         var type = this.props.type;
         return (
            <Column
                headerRenderer={this._renderHeader}
                label={type + (this.state.sortBy === type ? sortDirArrow : '')}
                width={100}
                dataKey={type}
                />
    }
});
```

The problem with this is that I get this error:
```
Uncaught Error: Invariant Violation: child type should be <FixedDataTableColumn /> or <FixedDataTableColumnGroup />
```

Can anyone please help me? I really want to have all the Heading logic in a separate module.

**Comment by ehzhang** [comment]
Hi @fullvlad! 

We actually maintain that the direct children of the table are either the Fixed Data Table Column group or fixed data table column. To get this kind of behavior, you may want to instead use a generator function to create those columns.

**Comment by fullvlad** [comment]
Thanks for the answer.
Do you have a sample code? I've never used a generator before.

**Comment by ehzhang** [comment]
As a really rough case, it's just a function that returns a react element, like:
```
function createColumn(id){
   // What you want here
   return <Column
     headerRenderer={renderHeader}
     label={id}
     //...your other props
     />
}
```

**Comment by ehzhang** [comment]
I've closed this since there hasn't been any activity - hopefully this has solved your problem. Let me know  if you still need help!

**Comment by Andreyco** [comment]
Is it possible to allow composition on Columns?
Something like this
```jsx
<Table>
  { makeColumnDraggable(<Column />) }
  { makeColumnDraggable(<Column />) }
  { makeColumnDraggable(<Column />) }
  { makeColumnDraggable(<Column />) }
</Table>
```
