### ISSUE TITLE
Let border-height be configurable

### ISSUE THREAD

**Issue by ssorallen** [facebook/fixed-data-table#240]
The border height of the table is currently fixed at 1px: https://github.com/facebook/fixed-data-table/blob/master/src/FixedDataTable.react.js#L39

```
var BORDER_HEIGHT = 1;
```

I'd like to integrate a table with no border, but the content area is then 2px shorter than it should be because FixedDataTable assumes 2px of its height are consumed by its top and bottom borders.

**Comment by pieterv** [comment]
I would recommend for this using a transparent border, this way you keep the width but it looks like its not there. Our default layout theme does this. In the future we are looking to make this stuff configurable via inline styles but its currently assumed in a lot of places

**Comment by chrisdrackett** [comment]
I'm having this issue as well. Using a transparent border doesn't fix the problem as it still takes up space.

**Comment by chrisdrackett** [comment]
did this get changed?
