### ISSUE TITLE
Automatically size row heights

### ISSUE THREAD

**Issue by mylowillem** [facebook/fixed-data-table#243]
What is the best way of automatically sizing row heights to fit the text inside. I know I can rowHeightGetter to manually change the size, but my row sizes are variable based on the contents. Is there some way I can the css "display: inline-block;" to the grid rows/cells to auto size without breaking the scrolling?

**Comment by ehzhang** [comment]
This is a pretty tricky problem since in order to virtualize the cells, we need to know an explicit height for each row. 
Currently, the best way I know of doing this is to use a heuristic to determine the expected row height for any given cell. :\

**Comment by pieterv** [comment]
The other thing you can do is in each cell on `componentDidMount` you check the contents height via `React.getDOMNode().outerHeight` (or something like that) then use that to reset the height of the row. The downside is this will be pretty hard to get to run a performant way. The auto content sizing is not something we are looking at adding to this library.

**Comment by altaihero** [comment]
can you provide code example about auto row height @pieterv
