### ISSUE TITLE
Altering an object's key-value being used in a cell renderer won't trigger a re-render

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#244]
This is weird. I have rows here with timestamps in some columns. I have just wrapped these timestamps into objects and am adding time zones into these objects.

One column called 'Received' is rendered like that:

```
  _renderReceived: (cellData) ->
    Time.timeToString(cellData.time, cellData.timeZone)
```

now the problem: when I loop through all rows and change the time zone of all these timestamp objects directly, then the table won't be re-rendered. Why?

**Comment by ehzhang** [comment]
Currently, the cells choose to re-render when a comparison of the previous data and the next updated data is different. 

It sounds like you are modifying the objects directly, so when the shouldComponentUpdate does a comparison of old vs new, it returns true as a direct comparison of an object reference to itself is true. So it won't update, since effectively oldCellData === newCellData. 

You may have more success in using something like Immutable.js to wrap the objects, or create an instance of a new object.

**Comment by binarykitchen** [comment]
Right, that's how React works and I am well aware of this. Still it doesn't work, I am creating new object references, yet the table cell doesn't get re-rendered. Looks like I ll have to check out Immutable.js then.

**Comment by ehzhang** [comment]
Are you triggering an attempt to render in the table at a higher level in any way when you go through the rows?

Perhaps by setting a state in the parent component may help?

**Comment by binarykitchen** [comment]
Already did, no luck.

**Comment by ehzhang** [comment]
Hmm. Actually, I believe that currently it's actually blocked at a higher level for the rowData. If the old rowData === new rowData equality passes then it will never think to go further. 

We're actually in the middle of changing this behavior, it's kind of frustrating.

**Comment by binarykitchen** [comment]
Yes it is frustrating.

**Comment by binarykitchen** [comment]
For now, I have figured an ugly hack using `_.clone()` like that

```coffee
  getRow: (index) ->
    row = @_getCurrentPageResults()?[index])

    # using this ugly hack because of https://github.com/facebook/fixed-data-table/issues/244
    # in short: we need a new object reference to force this being re-rendered
    if @props.forceUpdate
      row = _.clone(row)

    return row or null
```

but in future, better inspect the contents inside a row when deciding whether to re-render or not.

**Comment by ehzhang** [comment]
For performance reasons, we're not going to inspect the contents of a row and do any sort of deep comparison.

In the future, we won't be choosing re-renders based on data, but letting you choose to do it based on your own cell components and your own shouldComponentUpdate functions.

**Comment by rileytg** [comment]
this behavior has brought me to :sob: over the last few hours.

so in future versions, you will allow us to provide something like shouldComponentUpdate function to Table or Column?

**Comment by binarykitchen** [comment]
IMO contents of a row should be inspected. That's a very legit use case to alter the contents of a single cell.

**Comment by binarykitchen** [comment]
I am not worried about performance here because we only show about 20 rows here and paginate through the next 20 rows with buttons.

If you are so worried about performance, how about a new option to enable/disable cell content inspection?

**Comment by ehzhang** [comment]
Inspecting arbitrarily deeply nested row objects isn't something we want to do as a part of the table, and adding to the API just makes the table more bloated. The table itself shouldn't be handling your data anyway, and that's a behavior we'd like to change.

Please see #221 for more information on the next release that will happen later this week. I'll be making updates to documentation and description in preparation.

**Comment by kabordonaro** [comment]
Is there any progress on #221?

**Comment by jasongonzales23** [comment]
+1

**Comment by binarykitchen** [comment]
still no action here?

**Comment by wcjordan** [comment]
@binarykitchen This repo isn't very active, but if you want to file on [our fork](https://github.com/schrodinger/fixed-data-table-2), we're happy to look into it there.

Something like our [Data Context Example](http://schrodinger.github.io/fixed-data-table-2/example-context.html) may help in this case.

**Comment by binarykitchen** [comment]
@wcjordan oh, not very active? how come?

**Comment by wcjordan** [comment]
The Facebook maintainers haven't had the time to work on it. See #468 and #408 for more discussion.

At Schrodinger, we're committed to maintaining the repo and pulling in PRs.  Also hopefully fostering the community.  We've been adding performance improvements over the last year, and aim to land a migration to cleaner state management with Redux sometime in the next couple months.

**Comment by binarykitchen** [comment]
ah, thanks heaps for the links and comments - have missed all that out

guess i ll close this issue as "obsolete" then.
