### ISSUE TITLE
Paging data

### ISSUE THREAD

**Issue by lastlegion** [facebook/fixed-data-table#256]
Does fixed-data-table support pagination? Am unable to find any examples.
How do you guys deal with large data in your tables?

**Comment by ehzhang** [comment]
Fixed Data table does not have pagination built in, if that is your question. 

Rather, it will render whatever data you give it through the rowGetter. Changing a page means that you would just supply it with different data (presumably a second pages worth). 

I'm not certain what you mean by the second question - the table works with large numbers of rows by virtualizing the row position to render only what is in the viewport.

**Comment by Enet4** [comment]
Even if performance is not a concern, it seems that FixedDataTable does not support a separation of entries by pages right off the bat. This still contains some tricky logic, such as which page numbers to show and how to draw them.

**Comment by ehzhang** [comment]
Yup, this is true. The table is just the table. We don't intend to support these features as it would make the table less flexible in the process.

**Comment by lastlegion** [comment]
Yes but it would be great to have an example of this implemented on the examples page.
