### ISSUE TITLE
When using require, the table throws "Cannot read property 'PropTypes' of undefined"

### ISSUE THREAD

**Issue by Lastalas** [facebook/fixed-data-table#258]
We are on : FixedDataTable v0.4.6 

This is from our requirejs.config:
            paths: {
                react: 'vendor/react',
                FixedDataTable: 'vendor/fixed-data-table'
            }

I'm calling it via require in this fashion:
     require(['react', 'DataTable'], function (dt){
              console.log (dt)
     })

I get this error: Uncaught TypeError: Cannot read property 'PropTypes' of undefined

It's loading react appropriately in the beginning, since the table can start initializing.  It looks like I am having trouble with the abstraction for webpack_require(29).  It fails at this line:

	var React = __webpack_require__(29);
	var PropTypes = React.PropTypes;

Any thoughts?  The full stack trace gist is: https://gist.github.com/Lastalas/a152d8fb26c92e4c7c29

Thank you for your help

**Comment by cosminnicula** [comment]
@Lastalas I've used FixedDataTable with Webpack without a RequireJS config. Take a look here and see if it helps you https://github.com/cosminnicula/react-ui-components

**Comment by Lastalas** [comment]
@cosminnicula Thanks for the help.  We ended up killing requirejs all together and going with browserify.
