### ISSUE TITLE
Allow Column label prop as object PropType

### ISSUE THREAD

**Issue by MandarinConLaBarba** [facebook/fixed-data-table#260]
I have run into an issue where I need to make column header cells editable. However the `FixedDataTable` does not perform a render pass unless the `FixedDataTableColumn` node receives a mutated `label` property.

In my use-case, I allow columns to be editable, and have a custom `headerRenderer` to that end. Since the `Column` doesn't perform a render unless the `label` has changed, I've changed the `label` prop to be an object with a shaped similar to this:

```
let column = {label: 'my column', editing: true};
let node =
 <Column
          label={column}
          headerRenderer={this._columnHeaderRenderer}
          ...
          />
```

This actually works, but of course I get a warning due to PropType constraints:

```
Warning: Failed propType: Invalid prop `label` of type `object` supplied to `FixedDataTableColumn`, expected `string`.
```

I would like to propose that the `FixedDataTableColumn` allow for `React.PropTypes.any` for the `label` property.

**Comment by jasongonzales23** [comment]
+1

**Comment by pieterv** [comment]
Check out the `0.6.0` release with this there are no limitations on what can be passed to a cell since we don't own any of this state.
