### ISSUE TITLE
Automatic width of column?

### ISSUE THREAD

**Issue by lastlegion** [facebook/fixed-data-table#269]
Hi,
Is there any way of automatically set the width of columns to the width of the content?
Much like the css `width:auto` property.

**Comment by cesarandreu** [comment]
I don't think there's an easy way to know the width of a column before rendering it... So it's unlikely you'll get this.

**Comment by pieterv** [comment]
Sorry there is no standard way in the FixedDataTable to do this, in theory you should be able to build this in your cell by measuring all the column content after render then set the width. This is not an API we expect to add to the table since it would be very hard to do it a performant way.

**Comment by tlrobinson** [comment]
> you should be able to build this in your cell by measuring all the column content after render then set the width

This is what I'm doing. Initially I render the cells to be their full widths (either give the columns very wide widths or ensure they can overflow their container) then in componentDidUpdate I measure the cell widths and set a state variable with them to be used for the Column widths on all subsequent renders. It happens fast enough you don't see the incorrectly sized columns (but if it did you could hide the table or show a loading screen or something on top)

Be aware that it will only take into account the visible rows (and the few extra buffer rows) but usually it works ok, depending on your data.

Here's my `componentDidUpdate`:

```
    componentDidUpdate() {
        if (!this.state.columnWidths) {
            let tableElement = React.findDOMNode(this.refs.table);
            let columnWidths = [];
            for (let rowElement of tableElement.querySelectorAll(".fixedDataTableRowLayout_rowWrapper")) {
                for (let [index, cellContentElement] of Object.entries(rowElement.querySelectorAll(".public_fixedDataTableCell_cellContent"))) {
                    columnWidths[index] = Math.max(columnWidths[index] || 0, cellContentElement.offsetWidth);
                }
            }
            this.setState({ columnWidths });
        }
    }
```

**Comment by ayozebarrera** [comment]
I have a Table that generates columns based on the header text width. So I have a function with two parameters. The first parameter is the header text and the second one is the font that you are using.

This is the function:
```es6
getTextWidth(text, font) {
    let element = document.createElement('canvas');
    let context = element.getContext('2d');
    context.font = font;
    return context.measureText(text).width+24;
  }
```
**I'm adding 24px to the final width for extra padding*


And this is how I use it:
```es6
getTextWidth('hello', 'bold 14px Roboto, sans-serif')
```

Result screenshot:
![instantanea8](https://cloud.githubusercontent.com/assets/6180188/12261524/8cc4ab4e-b919-11e5-997c-e34d414e85a9.png)


hope it helps ^^
