### ISSUE TITLE
In ES6 "this" is undefined in rowGetter

### ISSUE THREAD

**Issue by jasongonzales23** [facebook/fixed-data-table#270]
Following the vanilla example but using ES6, my rowgetter function threw an error claiming that 'this' was undefined. Same exact code with React.createClass throws no such error. Maybe this is less of an issue with fixed-data-table and more with an understanding of how ES6 classes work though.

**Comment by ehzhang** [comment]
If you're using the ES6 class syntax for react components, you will have to bind `this` when you use rowGetter (which might be, for example, in your render() function).

See this: https://facebook.github.io/react/docs/reusable-components.html in the 'No autobinding' section.

**Comment by pieterv** [comment]
Yeah you likely are missing a bind somewhere.
