### ISSUE TITLE
Current Version Not Compatible with React 0.14 

### ISSUE THREAD

**Issue by imorrison** [facebook/fixed-data-table#283]
Looks like the current version of fixed-data-table is not compatible with React 0.14. In particular, there is use of `React.findDOMNode` which is deprecated in favor of `ReactDOM.findDOMNode`. 

See this section: https://github.com/facebook/fixed-data-table/blob/1c183ba0ce975b9e94de49bf0be24ac606036499/src/Scrollbar.react.js#L318-L350

Are there plans to upgrade to 0.14?

**Comment by vvanscherpenseel** [comment]
+1

It seems that development on fixed-data-table has slowed down, any news on this?

**Comment by musbaig** [comment]
+1

**Comment by mychaelgo** [comment]
+1

**Comment by martinpesout** [comment]
+1

**Comment by vysinsky** [comment]
+1

**Comment by di5ko** [comment]
+1

**Comment by vojtech-dobes** [comment]
:100: 

If you have any plans different from developing this library further, please share that so we know where we stand :). Thanks so far for great piece of software!

**Comment by pleesha** [comment]
+1

**Comment by davidlashlee** [comment]
+1

**Comment by pieterv** [comment]
I have pushed out the `0.5.0-rc1` package which adds support for React `0.14, if someone can try it out and make sure its working for you i can publish the stable `0.5.0` release.

**Comment by musbaig** [comment]
Hmm, `0.5.0-rc1` appears to be working for my stuff, albeit, my use cases may not be exercising every `fixed-data-table` api. Still, thanks for the update!

**Comment by pieterv** [comment]
Thanks @musbaig! i have now published 0.5.0

**Comment by muraveill** [comment]
I am experiencing errors with version 0.5.0 and react 0.14, see here:
https://github.com/facebook/fixed-data-table/issues/298

Is it working for all except me ? Could you please share your package.json if it works for you, so that I could understand what dependency could cause the problem ?
