### ISSUE TITLE
Width props doesn't work with 100% value

### ISSUE THREAD

**Issue by mandado** [facebook/fixed-data-table#289]
Hi guys. Thanks for creating and maintaining this library. :)

I tried to set '100%' value in width prop in Table component but doesn't work.
How i can solve this?

**Comment by ehzhang** [comment]
The table requires an explicit pixel width in order to properly calculate the layout. You will need to set this value yourself.

**Comment by mandado** [comment]
How i can make this table responsive?

**Comment by pieterv** [comment]
You will need to listen to the window resize event and then update the table with when it changes, here is how we do it for the examples page: https://github.com/facebook/fixed-data-table/blob/cf28c0e78a3859c9a6e5d94fc84912e28d64f62a/site/examples/ExamplesPage.js#L100-L116

**Comment by muraveill** [comment]
This module helps a lot in this respect:
https://www.npmjs.com/package/react-dimensions

**Comment by mandado** [comment]
@muraveill i'm look this package. thanks.
