### ISSUE TITLE
Invisible rows with 0.5.0 release and React 0.14

### ISSUE THREAD

**Issue by muraveill** [facebook/fixed-data-table#298]
Hi,
I just upgraded fixed-data-table to the latest release (0.5) after upgrading React to 0.14 and all other packages accordingly, without changing my script.

Now wherever I had data tables, I still see the table frame, and when I inspect I see the data is here, but all rows (including header) appear blank, or shifted, or in the background or something, but invisible. When I scroll inside the table, I see changing some dom elements that contain `.fixedDataTableRowLayout_rowWrapper` elements, and with properties like
     
    style="position: absolute; transform: translate3d(0px, -196px, 0px); backface-visibility: hidden;"

Adding a border around them, I see the first borders appearing only when I scroll down a bit, and they disappear as I scroll further.

I get the same result with the simple example on the Getting Started page (https://facebook.github.io/fixed-data-table/). Is it because of bad support of `translate3d`, or do you have an idea of what is missing ?

**Comment by muraveill** [comment]
I found out that I can manually edit the css in the browser's dev tools to see the hidden lines, but it is highly suspicious, and attributes are set inside the html. I have to

- Set to 0 (down from table height) the height of the element `.fixedDataTableColumnResizerLineLayout_main.fixedDataTableColumnResizerLineLayout_hiddenElem.public_fixedDataTableColumnResizerLine_main`
  (but it is set inside the html `style` tag, so a css rule does not override it)

- Set to 0 (down from 50px) the height of `fixedDataTableCellGroupLayout_cellGroupWrapper` elements that have a `data-reactid="...$fixed_cells`
  (but in the css I don't know how to select only these and not the `...$scrollable_cells`)

Please give me some explanation as to how to fix this. Why do fixed cells take 50px in height if I don't have any anyway ?

**Comment by muraveill** [comment]
I could change these attributes on the fly by modifying the css attributes above with a bit of jQuery inside componentDidUpdate, but the problem persists for rows that were hidden and are created when the user scrolls down.

What mechanism makes the rows appear when scrolling down ? There seems to be no component (state) update. I really need to get around this.

**Comment by airwin** [comment]
same problem, rows are all invisible..
Reactv0.14.2 + F-D-Tv0.5.0

**Comment by airwin** [comment]
@muraveill Hey, I got the reason, see the changelog of (v0.4.0)[https://github.com/facebook/fixed-data-table/releases/tag/v0.4.0] 
The style file now separate into 2 files: `dist/fixed-data-table-base.css` and `dist/fixed-data-table-style.css`.

**Comment by muraveill** [comment]
Oh thank you for noticing that ! You saved my life ! It works now
