### ISSUE TITLE
Bottom row stays fixed and on top of the row above it

### ISSUE THREAD

**Issue by hharnisc** [facebook/fixed-data-table#3]
The bottom row is staying fixed while scrolling (it does still update when done scrolling). It sits above the row on top of it like this:

![screen shot 2015-01-28 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1388079/5950373/1610e9ae-a70e-11e4-880b-12a97c253456.png)

This happened after scrolling about 3/4 down scrolled up, and then back down again.

Chrome (Mac) Version

![screen shot 2015-01-28 at 4 54 14 pm](https://cloud.githubusercontent.com/assets/1388079/5950396/6fc7e1b4-a70e-11e4-8cf7-79ffc9cb5441.png)

**Comment by hedgerwang** [comment]
Hi @hharnisc 
The screenshot looks normal to me. 
Do I miss anything?

**Comment by pieterv** [comment]
Hmm interesting looks like it has scrolled the header down a little as well.

**Comment by hharnisc** [comment]
@hedgerwang if you look at `Kacey Lubowitz` row, just above the profile image. You'll see there's just a little bit of the profile image from the previous row behind it and cut off.

**Comment by wlis** [comment]
@hedgerwang Haven't you solved this issue with https://github.com/facebook/fixed-data-table/commit/a907bafe8403a82a057363af0bda271f76ea8fc0 ?

**Comment by wlis** [comment]
This was issue with the Image component we used. This is fixed now.
