### ISSUE TITLE
Support for Immutable.js?

### ISSUE THREAD

**Issue by johnnyji** [facebook/fixed-data-table#300]
Hey guys,

I've noticed that the `rowGetter` function must return an array. Would it be hard to add support so that we can use Immutable.List as well?

**Comment by thewillhuang** [comment]
you can also return an object as long as your dataKey is some sort of key on the object

**Comment by pieterv** [comment]
Hey @johnnyji check out the latest `0.6.0-rc1` release ([docs are here for now](https://github.com/facebook/fixed-data-table/tree/master/docs)). With this, the fixed data table no longer needs any data via the `rowGetter` so you can use whatever data structure you want :)
