### ISSUE TITLE
datakey for complex json type

### ISSUE THREAD

**Issue by laitang2000** [facebook/fixed-data-table#301]
Hi, 

Is it possible to get the datakey property to refer to a child object? e.g.  datakey='Driver.FirstName'
I have tried but it displays nothing.

Thanks

**Comment by thewillhuang** [comment]
```js
let Driver = {};
Driver.FirstName = '2000';

datakey={Driver.FirstName}
```

**Comment by pieterv** [comment]
Sorry its not possible with the current release. If you check out the latest `0.6.0-rc1` release ([docs are here for now](https://github.com/facebook/fixed-data-table/tree/master/docs)). With this, the fixed data table no longer needs any data via the rowGetter so you can access data however you want :)
