### ISSUE TITLE
Cannot read property 'releaseMouseMoves' of undefined

### ISSUE THREAD

**Issue by aphillipo** [facebook/fixed-data-table#302]
Hello,

I have a small issue with the fixed data table that is causing me some severe problems.

Essentially I have a fixed-data-table and when I navigate away with react-router I get an error and my app stops working :-1: 

Scrollbar.react.js:180 Uncaught TypeError: Cannot read property 'releaseMouseMoves' of undefined

Is the error...

I wondered if it is because of this line:

delete this._mouseMoveTracker;

I'll create a testcase later but I'll add this bug as a placeholder just in case it's been spotted and fixed (I did search first)!  Thanks so much for fixed data table it's really amazing.

**Comment by aphillipo** [comment]
This seems to only occur when I call .refresh() on a ref to the table.  Very strange.

**Comment by aphillipo** [comment]
This lovely bug is caused by having react inside a react modules npm.  Somehow webpack includes it twice.  Nice.

**Comment by anshulmalik1** [comment]
Hey, I am having the same issue. When I navigate to another route, I see this error in FixedDataTableColumnResizeHandle.react.js L109
Still don't know how to resolve this issue.
