### ISSUE TITLE
Basic Example is not working

### ISSUE THREAD

**Issue by bzums** [facebook/fixed-data-table#306]
The basic example you give in the readme is not working, is it? I get:

```Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).```

´´´Warning: Failed propType: Required prop `dataKey` was not specified in `FixedDataTableColumn`.````

```Warning: Failed propType: Required prop `rowGetter` was not specified in `FixedDataTable`.```

´´´Warning: Failed propType: Required prop `rowGetter` was not specified in `FixedDataTableBufferedRows`. Check the render method of `FixedDataTable`.````

```Uncaught TypeError: rowGetter is not a function```

Am I missing something?

**Comment by pieterv** [comment]
Sorry we are halfway through a release, the example in the readme is for the `0.6.0` release which is only released as `0.6.0-rc1`. You are welcome to try this out (it will be release properly very shortly) or the docs for the current release are on the site.
