### ISSUE TITLE
IE and iPad Scrolling

### ISSUE THREAD

**Issue by dehamilton** [facebook/fixed-data-table#310]
With the latest release, I can't scroll in the iPad or IE (11 or 10, but I can with 9). I have cloned the repo, built and run locally, and received the same results. 

I've seen that the examples use a scroll wrapper, but since I can't scroll the examples I'm not sure what benefit I would received from using it.

FWIW, I'm more interested in iPad help. Thanks for any suggestions.

**Comment by pieterv** [comment]
Oh thanks for the issue, i think i know what i might have missed when messing with the examples for the  latest release.
