### ISSUE TITLE
Scrolling page once on the top/bottom of table

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/fixed-data-table#33]
[Usual behavior](http://jsfiddle.net/mrakjos/01qcetg3/) for scrollable divs is that if you reach top/bottom via mouse scroll is that page continue to scroll..  But fixed-data-table eat all the scroll events when mouse is on top of it even if top/bottom is reached.

Would be possible to add this behavior in fixed-data-table?

**Comment by pieterv** [comment]
@jardakotesovec yes sorry the table should support this by default and we plan on implementing this soon. We should be able to see when the user gets to the bottom scroll point and stop preventing default at that point.

**Comment by nbostrom** [comment]
We have this as a blocker where I work. I would love to create a pull request, but since there are no tests I don't really dare :/

**Comment by TomClarkson** [comment]
I need this aswell. This is related to #84 Can you give me a heads up on how to fix this.

**Comment by pieterv** [comment]
This should be fixed in the latest release :)
