### ISSUE TITLE
Can we use fixed-data-table with react 0.13?

### ISSUE THREAD

**Issue by TomClarkson** [facebook/fixed-data-table#34]
The package.json requires "react": "0.12.x"

**Comment by pieterv** [comment]
Yes fixed-data-table works great with react 0.13 (internally Facebook uses react master), but you are right we should update the package to allow npm installing with react@0.13. We should be able to put out a new release pretty soon with this change.

**Comment by pieterv** [comment]
@TomClarkson I have released `0.1.2` which updates the package.json to support react `0.13.0` as well as `0.12.x`. Sorry i didn't get to this early but i couldn't get the package.json config to allow the beta version as a dependency.
