### ISSUE TITLE
Babel 6 compat

### ISSUE THREAD

**Issue by iilei** [facebook/fixed-data-table#347]
Are you already working on babel 6 compatibility?
Otherwise I'd be happy to file a PR - see https://github.com/iilei/fixed-data-table/tree/babel_6_compat :smile:

**Comment by pieterv** [comment]
Oh nice! Would love a PR for that.

**Comment by toddwildey** [comment]
+1

I'm having issues with FixedDataTable and the strict mode ES6 assumes.

**Comment by AgentME** [comment]
Babel 5 already adds 'use strict' to transpiled code, so there shouldn't be any new issues related to that if this is switched to Babel 6.
