### ISSUE TITLE
Uncaught ReferenceError: requestAnimationFramePolyfill is not defined

### ISSUE THREAD

**Issue by TomClarkson** [facebook/fixed-data-table#35]
I get this error when I scroll horizontally multiple times or resize multiple columns.

![error on multiple scrolls or resizes](https://cloud.githubusercontent.com/assets/2054503/6141075/60f39500-b205-11e4-9bf6-7e5f75f8bf30.png)

Here is the code I am using (it is mostly the code from the resize example with some data) https://github.com/TomClarkson/fixeddatatable/blob/master/scripts/index.js

**Comment by pieterv** [comment]
Hey @TomClarkson thanks for the awesome bug report! From looking through your code it looks like a webpack related issue, see https://github.com/facebook/fixed-data-table/issues/20#issuecomment-73403088. We should have a fix out for this pretty soon!

**Comment by pieterv** [comment]
Should be fixed in v0.1.1, let me know if not.
