### ISSUE TITLE
How to implement variable row height?

### ISSUE THREAD

**Issue by snowinferno** [facebook/fixed-data-table#377]
The documentation indicates a feature of fixed-data-table is that you can have variable row heights.
None of the examples show this and it isn't obvious how to accomplish this task.

I have a button in the row to expand for showing more detail.
When I render the Cell in the column (I check for the presence of `props.rowIndex` in a Set containing indices of items that have been expanded), I change the height of the cell (and each other cell in the table row) to be larger. This doesn't seem to have any effect as the row height doesn't change for the row at all.

**Comment by KamranAsif** [comment]
You need to use [rowHeightGetter](http://facebook.github.io/fixed-data-table/api-table.html#-rowheightgetter-) defiend at the table level.

**Comment by snowinferno** [comment]
`rowHeightGetter` is exactly what I was looking for. Thanks!
