### ISSUE TITLE
Touch Events

### ISSUE THREAD

**Issue by ofersadgat** [facebook/fixed-data-table#39]
I do not understand how touch events work with this library. There is no call to ```React.initializeTouchEvents(true)``` and React pre 0.13 doesnt even have TouchEvents included in the default build. Did you use a custom library for the website or am I missing something? For some reason your event handler in touchable area is being called where mine isnt, did you do anything special to achieve this?

**Comment by ofersadgat** [comment]
Upon further inspection it appears that you are using ZyngaScroller for this purpose in which case I ask why ```TouchableArea``` exists, because none of its events should be thrown?

**Comment by jardakotesovec** [comment]
@ofersadgat I have same question. Did you figured out the answer since you closed it?

**Comment by jardakotesovec** [comment]
Nevermind, answer is pretty much here #4
