### ISSUE TITLE
Any future updates for fixed-data-table coming? (Fixed-Data-Table to support React^15.0.2)

### ISSUE THREAD

**Issue by DDChiang** [facebook/fixed-data-table#394]
I'm currently trying to upgrade my project's "react" and "react-dom" versions to 15.0.2, but I keep getting an npm error from fixed-data-table module because fixed-data-table module only supports react versions less than 15.0.0. 

I don't see any breaking changes when upgrading to the newer react version that majorly affect fixed-data-tables (you guys can be the best judge), but at the same time, the npm install errors for "unmet peer dependencies" are really freaking me out.

Anyways, my hopes are that this library will be continued and up-to-speed as I'd like to keep using fixed-data-table in my projects.

**Comment by jonaswindey** [comment]
+1

pretty strange to see an "official" facebook react module not being maintained

**Comment by jonaswindey** [comment]
For now, untill my PR is merged, you can use my fork if you want to use react 15.x

`"fixed-data-table": "git://github.com/trinit/fixed-data-table#master",`

**Comment by FredericHeem** [comment]
@jonaswindey: do you mind to create a PR if not already done ?

**Comment by jonaswindey** [comment]
Done

**Comment by naddeoa** [comment]
Just going to link the PR here. This issue shows up in google searches.

https://github.com/facebook/fixed-data-table/pull/396

**Comment by KamranAsif** [comment]
Hey folks,

My group is using this library very actively, and we plan to maintain it. 
We've already merged in some pull requests (Notably column drag reorder) and have done several bug fixes and have support for react v15.
We also threw up some new examples to help folks!

Check it out here: https://github.com/schrodinger/fixed-data-table

**Comment by zpao** [comment]
0.6.1 (just shipped) should work with React v15.
