### ISSUE TITLE
Scrolling doesn't work on my iPad

### ISSUE THREAD

**Issue by fingermark** [facebook/fixed-data-table#4]
Trying out the demo and both horizontal and vertical scrolling don't work on my iPad.

**Comment by kamilogorek** [comment]
@fabiomcosta 
> FixedDataTable does not support touch devices, but eventually will.

**Comment by pieterv** [comment]
Unfortunately the table doesn't directly have touch support at this point, but stay tuned its coming soon!

**Comment by pieterv** [comment]
@fingermark try it now :) We added touch support to the examples via the Zynga scroller.

**Comment by DjebbZ** [comment]
Tested (iPhone 5C, iOS 7, Safari), and while it works, the behaviour is somehow weird, because when I scroll up/down, my finger doesn't move perfectly vertically, so I see the right part of the table sliding a little left or right too when it's sliding up or down. Otherwise the animation is smooth.

Of course such a big table isn't pratical at all on a small phone, even in landscape.

**Comment by wlis** [comment]
@DjebbZ Thanks for testing it, If you look at code, we haven't actually implemented touch support inside the table. Table scrolling can be also controlled by props and we just wrapped it in ZyngaScroller in examples. In this way you could use any touch event handler and scrolling engine to customise behaviour of scrolling on touch devices.

**Comment by fabiomcosta** [comment]
I think I was mistakenly tagged on this thread hah

**Comment by fingermark** [comment]
It works, but it's no where as fast or smooth as it is on desktop.  I really like where this is going, though.

**Comment by martinpesout** [comment]
I see that you are using ZingaScroller to achieve scrolling on touch devices. But if you check https://github.com/zynga/scroller you can see that Zinga Scroller is without support and update over 3 years. Do you think that it's still good idea to achieve scrolling with outdated library? Is there any live alternative for this?

**Comment by NerdCowboy** [comment]
@martinpesout Did you you find any alternatives?

**Comment by martinpesout** [comment]
@NerdCowboy no, I'm using ZingaScroller in the end :smile: I think that this library works. I had to extend classes for better rendering performance support:

```
.public_fixedDataTable_header,
.fixedDataTableLayout_rowsContainer > * {
	transform: translateZ(0);
}
```

This improve scrolling performance just a bit and fix weird problem on iOS Safari, when I had disappearing header for a while when interact with cells inside (for example I placed checkbox into table). 

Interesting is that during my frontend development I've found a lot of problems with rendering on iOS Safari or Chrome (and problems weren't related only to fixed-data-table) and every time I solved it by some trick with `transform: translateZ(0);` :smiley:

**Comment by mtando** [comment]
https://facebook.github.io/fixed-data-table/example-object-data.html  -> I can only scroll horizontally up to ZipCode column on my chrome (iOS iphone 6 device). Is there a way to fix this?

**Comment by wcjordan** [comment]
@mtando this repos maintainers are no longer active, but we've created a maintained fork here:
https://github.com/schrodinger/fixed-data-table-2 (under fixed-data-table-2 on npm)

We also recently added a touch scroll support which I believe will work for your case.  It can be enabled by passing a touchScrollEnabled prop to the Table as in the example [here](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/TouchScrollExample.js).

Please try it out and file any issues you see on our repo.

**Comment by dhirajbasukala** [comment]
@martinpesout were you able to use ZingaScroller with animation also working ?  I'm also using FDT 0.6.3 ( recently updated) and trying to add scrolling to mobile device as well. The farthest I got is able to make it work without animation by removing call to doTouchEnd in handleTouchEnd.  With this(doTouchEnd) method called the scroll animation reset back to left 0 and top 0, it just won't scroll down. It shows bouncing animation back to left 0 , top 0. The animation worked only when I called _onContentHeightChange from handleTouchStart method. I related to the example provided from the zyngascroller webiste (EasyScroller one). I'd really appreciate if you can share what you've achieved so far. 
Any help is appreciated.
