### ISSUE TITLE
Override column group header with groupHeaderRenderer

### ISSUE THREAD

**Issue by TomClarkson** [facebook/fixed-data-table#41]
I am trying to use the group groupHeaderRenderer method to customise a column group header but it doesn't seem like it is getting called.

https://github.com/TomClarkson/fixed-data-table-column-group-headers/blob/master/site/examples/ColumnGroupsExample.js#L46

**Comment by TomClarkson** [comment]
I was unable to push my pull request but here is my change to add in groupHeaderRender as per the docs https://github.com/TomClarkson/fixed-data-table/pull/1/files

**Comment by pieterv** [comment]
@wlis was this something you fixed?

**Comment by TomClarkson** [comment]
@pieterv Can you please use groupHeaderRenderer prop as the cellRenderer for ColumnGroups

Here you can see the problem and the line of code that is needed to fix it

 https://github.com/TomClarkson/fixeddatatable/blob/master/README.md

**Comment by wlis** [comment]
This has been fixed in #151
