### ISSUE TITLE
Warning: Unknown prop `rowIndex` on <div> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by azamuddin** [facebook/fixed-data-table#434]
I just try the example both on version 0.5 and 0.6. And it says

    contentscript.bundle.js:1378 Warning: Unknown prop `rowIndex` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by FixedDataTableCell)
    in div (created by FixedDataTableCell)
    in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
    in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTableBufferedRows)
    in div (created by FixedDataTableBufferedRows)
    in FixedDataTableBufferedRows (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by TransitionTable)
    in TransitionTable (created by App)
    in div (created by App)
    in div (created by ExtensionContainer)
    in div (created by ExtensionContainer)
    in ExtensionContainer (created by App)
    in div (created by App)
    in App

What am I missing here?

**Comment by zpao** [comment]
Just pushed a fix (should be anyway). I'll ship that as 0.6.3.
