### ISSUE TITLE
Scrolling left on Chrome goes back

### ISSUE THREAD

**Issue by djkirby** [facebook/fixed-data-table#439]
![chrome](https://cloud.githubusercontent.com/assets/2212806/17484787/9d5a6ae0-5d59-11e6-9c12-ebd2d9edfa8a.gif)

In Chrome I'm finding it impossible to scroll left on the table, it's just triggering the 'back' gesture in Chrome. Any workarounds for this?

**Comment by KamranAsif** [comment]
What version of chrome are you on? Someone reported a similar issue on our fork: https://github.com/schrodinger/fixed-data-table-2/issues/36

**Comment by djkirby** [comment]
@KamranAsif Version 52.0.2743.116 (64-bit).

**Comment by djkirby** [comment]
To clarify, the scrolling itself works, but using a Magic Mouse or Macbook track pad causes the 'back' behavior

**Comment by KamranAsif** [comment]
I'm on OS X 10.11.4 with Chrome Version 52.0.2743.116 (64-bit) and I can't reproduce this on our fork or this one. Are you able to reproduce it consistently?

**Comment by djkirby** [comment]
Since restarting chrome I haven't experienced this behavior, so we can probably close this issue.

**Comment by djkirby** [comment]
@KamranAsif  Btw what is different in your fork? Should it be used over this repo?

**Comment by KamranAsif** [comment]
This library hasn't seen a lot of maintenance (you can just look at the number of open issues and PRs)

Our fork has more features, documentation, examples and bug fixes. We are trying to get the community more involved so feel free to check it out and contribute!

**Comment by sheerun** [comment]
This is still an issue
