### ISSUE TITLE
Question: how to highlight row selection?

### ISSUE THREAD

**Issue by kayazinc** [facebook/fixed-data-table#442]
Use-case
===
1.  User clicks on the cell on the table.
2.  The row on the table is highlighted.

I tried the solution on https://github.com/facebook/fixed-data-table/issues/189 and the following is the result:
![watchlist-row-highlighter](https://cloud.githubusercontent.com/assets/19774010/17612767/452be574-6088-11e6-9fc4-d0b6ad169404.PNG)

See the blue circle, there is a empty "space".  Is there anyway to fill the entire row, i.e. fill the empty space too?

**Comment by csatish** [comment]
@kayazinc 
Can you please share some code to show selection highlight?

**Comment by kayazinc** [comment]
@csatish, at cell definition, you can set the style.
```
const DateCell = ({rowIndex, data, col, ...props}) => (
  <Cell {...props} className="highlight">  // set the highlight style
    {data.getObjectAt(rowIndex)[col].toLocaleString()}
  </Cell>
);
```

**Comment by varenya** [comment]
Cell class applies at cell not the row level right?

**Comment by Dhruv56** [comment]
You can use **rowClassNameGetter** to apply class on a Row. Refer to [documentation](https://facebook.github.io/fixed-data-table/api-table.html) for more details

**Comment by varenya** [comment]
I tried that but it works on cell only...

**Comment by undejavue** [comment]
+1, want to highlight whole row on hover; no success (

**Comment by Rahadian347** [comment]
i can't use rowClassNameGetter to change row's background color , it'cant change row's background color, only cell background, any idea ?
