### ISSUE TITLE
Ellipsis for text overflow in table cell?

### ISSUE THREAD

**Issue by mirko77** [facebook/fixed-data-table#454]
Hi there,

I was wondering if it is possible to have the table behave like when I set `table-layout: fixed;` on the table and then `text-overflow:ellipsis` on the cell, so the text will always be on a single line with `...`

I tried to play with the css but no luck...

**Comment by tkirda** [comment]
Yes it is possible. Wrap your content into div with the class and set style on that class:

```
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
```

**Comment by mirko77** [comment]
I tried but it does not work, the text is on a single line and trimmed but the overflow is not replaced by the ellipsis. 


I also tried on the example [here](https://facebook.github.io/fixed-data-table/example-object-data.html) adding long text to a cell and then play with the css but I get the same result, no ellipsis showing

See [screenshot](https://drive.google.com/file/d/0B6K16Oe-ZJjeMGs3WkxLa3pjczA/view)

**Comment by tkirda** [comment]
That's right, I did not include all the details. This should work:

```
.cell {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    box-sizing: border-box;
    display: block;
    padding: 8px;
    width: 100%;
}

.cell-overflow {
    box-sizing: border-box;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

<div class="cell">
	<div class="cell-overflow">
		Long content...
	</div>
</div>
```

**Comment by mirko77** [comment]
It does work indeed!

Many thanks

**Comment by FredericHeem** [comment]
In my use case, `overflow:hidden` is also needed in the `cell-overflow` class

**Comment by alexedev** [comment]
Thanks, you just saved my day!

**Comment by mobimation** [comment]
Now in 2017 useful with fixed-data-table-2 also !

**Comment by khurshed52** [comment]
.cell-ellipsis {
    max-width: 1px;
    width: 20%;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

**Comment by sdhhqb** [comment]
No need to use two div wrappers, just set 
```
table-layout: fixed;
```

**Comment by tuanvayn** [comment]
> No need to use two div wrappers, just set
> 
> ```
> table-layout: fixed;
> ```

Many thanks btw all of the columns have the same width size. how to make size of the first column is smallest?

**Comment by tkirda** [comment]
There is **width** property on the column.

**Comment by SevenZark** [comment]
If you go this route, you HAVE to manually set a width on every column on every table in your entire app, if you want anything other than forced equal-width columns. This is a nightmare in a large application. I still have not found a solution which preserves one of the biggest advantages html tables give us - intelligent auto-sizing of columns. With this approach you're hobbling that completely.
