### ISSUE TITLE
Rename .public_fixedDataTableRow_highlighted to .public_fixedDataTableRow_odd/even

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#47]
I think I would rename the CSS class from

```css
.public_fixedDataTableRow_highlighted
```
to
```css
.public_fixedDataTableRow_odd // (or _even)
```

Because that's more precise. CSS class names should describe the content, not the appereance. Highlight means it's highlighted, selected for a certain purpose which isn't the case here.

**Comment by pieterv** [comment]
Good point! This makes a lot of sense, feel free to send a PR for this change or i can do it at some point :)

**Comment by binarykitchen** [comment]
No rush, take your time to change this. Cheers

**Comment by matrinox** [comment]
:+1:

**Comment by ehzhang** [comment]
For v0.4.0, rows now include both classes `.public_fixedDataTableRow_highlighted` and either `.public_fixedDataTableRow_odd` or `.public_fixedDataTableRow_even`!
