### ISSUE TITLE
Example: With JSON Data Bug

### ISSUE THREAD

**Issue by arthurchipdean** [facebook/fixed-data-table#475]
In chrome on this page: https://facebook.github.io/fixed-data-table/example-object-data.html

It seems like I can scroll past the end of the table by grabbing the table scroll handle and scrolling down. 

Here is a pic:
![image](https://cloud.githubusercontent.com/assets/1786637/22261466/f78d9968-e221-11e6-825b-3e121fbc9740.png)

**Comment by KamranAsif** [comment]
We've fixed this in our fork: https://schrodinger.github.io/fixed-data-table-2

We also have bug fixes, new features and better documentation.

**Comment by arthurchipdean** [comment]
Awesome. Thank you
