### ISSUE TITLE
onDoubleClick event does not seem to be supported

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#48]
Looks like I cannot assign a `onDoubleClick` event handler on a row. Can you confirm it's not supported or missing?

**Comment by pieterv** [comment]
I would say its missing, we are missing a few events like this. If you want you can defined this on a individual cell via a `cellRenderer`. But we should look to adding these events to Rows.

**Comment by binarykitchen** [comment]
Adding these events to Rows would be great. Any chance this can be done soon?

Meanwhile I'll hack my code with a `cellRenderer`. Are there any examples for that?

**Comment by pieterv** [comment]
We can probably look at doing this soon, although a pull request for these changes would certainly speed up the process :P

**Comment by binarykitchen** [comment]
A PR from my part would take a bit too long. Have to deliver some code today, so I would like to monkey patch this with a cellRenderer for now. Can you show me how?

**Comment by pieterv** [comment]
Something like this should work (i haven't tested it):
```
function handleDoubleClick(index, event) {
  // handle dbl click
}

function cellRenderer(content, index) {
  return (
    <div styles={{height: '100%'}} onDoubleClick={handleDoubleClick.bind(null, index)}>{content}</div>
  );
}
```

You might need to move the default cell padding to this inner element to capture all the clicks.

**Comment by binarykitchen** [comment]
Thanks but this is not working properly because it messes with the existing `onRowClick` handler I have on the table :(

**Comment by crisward** [comment]
I realise this is a bit late, but you can simulate a double click like this.

```javascript
Grid = React.createClass({
  clicktime:0
  onSelected:function(e,idx){
    if ((new Date - @clickTime) < 500){
      this.onDblClick(idx) 
    }
    this.clickTime = new Date()
    //click stuff here
  }

  onDblClick:function(idx){
    //your double click 
 }
...
})
```
This is the technique I'm using

**Comment by binarykitchen** [comment]
thanks, already figured out a similar, temporary hack ...

**Comment by franleplant** [comment]
Another thing related to this is to handle row selection, it'll be nice to allow the user the know better the row is clickable and if the row is selected by a single click the the user might want to try double clicking for further actions.

**Comment by ehzhang** [comment]
This issue has been addressed in the most recent version (v0.3.0), which includes the onRowDoubleClick property in the Table component.

**Comment by binarykitchen** [comment]
Thanks @ehzhang but I won't check out v0.3 until you have updated the changelog at https://github.com/facebook/fixed-data-table/releases

**Comment by ehzhang** [comment]
@binarykitchen changelog has been updated.
