### ISSUE TITLE
Curious about future milestones of this project

### ISSUE THREAD

**Issue by nextofsearch** [facebook/fixed-data-table#485]
Hi,

I am wondering if this project is still active enough for me to choose for my future product, which intensively use tables with large data sets. I've recently migrated to React but am still using DataTable (dependent on jQuery) and looking for an alternative. The decision will make huge impacts on the project so I get to be cautious about it.

This project looks solid as a start but when I checked the release history and PRs, it got slow and the latest release was from last July. I am wondering if this project has milestones to move forward and someone can share it with me.  I will appreciate any comment. 

Thank you!

**Comment by wcjordan** [comment]
Hey @nextofsearch, this repo is no longer maintained, but we maintain [a fork at Schrodinger](https://github.com/schrodinger/fixed-data-table-2).  We've put together a [roadmap here](http://schrodinger.github.io/fixed-data-table-2/roadmap.html) and try to fix any bugs which popup and assist with anyone adding new functionality through a PR.  Another popular library to look at is [React-Virtualize](https://github.com/bvaughn/react-virtualized) which allows performant rendering of large lists and grid data.

**Comment by nextofsearch** [comment]
@wcjordan Thank you so much!
