### ISSUE TITLE
Firefox scrolling performance

### ISSUE THREAD

**Issue by matthughes** [facebook/fixed-data-table#5]
Scrolling on Firefox constantly stutters.  Tested on FF 35.01 on OS X.  Chrome on the same machine is buttery smooth.

A scroll bar for the document keeps appearing while trying to scroll inside the table.

**Comment by pieterv** [comment]
Hey @matthughes this should be working now on the site! Thanks for the report!

**Comment by matthughes** [comment]
Yup, much better now.  Thanks.

**Comment by pieterv** [comment]
Awesome!

**Comment by willywongi** [comment]
Main page and example page are still stuttering here: FF 35 on OS X 10.9.5. Same goes on Chrome as @matthughes. I inspected the page and I see the fix linked to this thread, but scrolling is still slow.

**Comment by matthughes** [comment]
@willbailey Slow or stuttering?  FF is still slower than Chrome with this fix, but the stuttering is completely gone for me.  I tried my browser at bunch of different dimensions and didn't see it.  Only difference is you're on 10.9.5 and I'm on 10.10.2 but I can't believe that would matter.

**Comment by pieterv** [comment]
@willywongi FF does seem to give a lower frame rate to Chrome, i will reopen this to see if we can find a way to fix this.

**Comment by willywongi** [comment]
On my Mac, with 10.9, scrolling is definitely slow (< 1FPS), both using scroll wheel and dragging the scroll bar. Checking this issue with a colleague I noticed that on his Mac, with OS X 10.10, scrolling is good (smooth).

**Comment by jusio** [comment]
I don't have any significant performance scrolling problems, but I've noticed one thing:

translate3d seems to be applied to each row separately and it seems that during scrolling each row is always updated on scroll event. It seems that it makes scrolling dependent on viewport size (e.g. how many rows are visible on the screen). 

Guys from Github used different approach for scrolling in Atom (http://atom.io).
They've created a giant div (it has a height enough to contain all rows) where they put all the rows. transform3d is applied only to that root div. Individual rows are positioned inside the div using top position. When some rows are way to far from viewport, they are repositioned to be after/before viewport (so there is same number of invisible rows before/after viewport, they seem to keep at least two invisible rows before/after viewport).
The advantage of this approach is that there is a constant number of dom updates, scrolling generally is achieved by updating a single div, and only rows which are too far from viewport are being repositioned (the rest of the rows is not touched) vs current fixed-data-table approach  where every single visible row position is updated on each scroll.

**Comment by pieterv** [comment]
@jusio Awesome idea, i had a poke around in atom and like you said it looks like it has some good ideas we might be able to use! I use atom as my editor and have never seen it drop frames.

**Comment by nbostrom** [comment]
@jusio 's suggestion would probably also solve the other scroll issues, like page up/down, arrow keys, scroll locking, etc.

**Comment by pieterv** [comment]
@nbostrom @wlis implemented @jusio's suggestion see #96, this is in the current master if you wanna check it out. We are seeing some pretty good perf wins in Firefox but its not perfect as a row pre-rendering doesn't seem to be working as effectively as in other browsers since Firefox doesn't seem to paint pixels until they are completely visible.
