### ISSUE TITLE
What is wrong with this JSFiddle?

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#55]
http://jsfiddle.net/michaelheuberger/4jg2z343/17/

The table is not rendered properly. But the code is very similar to the example on the README.md on https://github.com/facebook/fixed-data-table#getting-started .... what's wrong?

**Comment by pieterv** [comment]
A couple of things, first you need to use gitraw so it gets the right headers for JS, then you will need to polyfill `Object.assign` which is where it gets a little hard :P 

I was able to get it going with JSBin: http://jsbin.com/zocituvuyi/2/edit

**Comment by binarykitchen** [comment]
Ah, that explains @pieterv thanks! But why can't I modify (tick/untick) the checkboxes in your example?

**Comment by pieterv** [comment]
You need to define an onChange handler and then set the value, see: http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by binarykitchen** [comment]
Okay, here is the next problem:
http://jsbin.com/jonimu/2/edit

I have an array of selected states. But somehow this is not updated. Any clues?

**Comment by binarykitchen** [comment]
Maybe it's a problem with `shouldComponentUpdate()`?

**Comment by binarykitchen** [comment]
@pieterv Do you think you can help me here please?

**Comment by pieterv** [comment]
http://jsbin.com/kuyixo/1/edit?js,output

The table wont rerender a cell unless the data for the cell changes, and since we were by passing the cells data input and referencing the state directly in the cellRenderer it didn't know the data had changed and hence didnt know to rerender.

**Comment by binarykitchen** [comment]
Ah, @pieterv, that explains. Are you saying react components won't re-render unless any attached state has changed?

Ok, now I have added some more code (a onRowClick handler) and here is the next problem: an error is thrown on a row click. What am I doing wrong?

http://jsbin.com/laxifo/2/edit

Thanks!

**Comment by pieterv** [comment]
You had a typo, you were setting the data for the clicked row back in place of the rows: http://jsbin.com/ribulu/2/edit

More correctly cellRenderers will not be called again unless the cells associated data changes.

**Comment by binarykitchen** [comment]
Ah, good. We are getting closer. And now, the last problem:
http://jsbin.com/kenigu/2/edit

It does not work anymore, when I change the row items into objects. Why @pieterv?

**Comment by pieterv** [comment]
http://jsbin.com/temufa/2/edit

So you need to create a new instance of your object data, its the same reason i was `slice()`ing the array. If you don't do this you will still have referentially equal objects and `oldObject === newObject` will still equal true. The react update helper might be helpful if you are doing lots of these updates.

**Comment by binarykitchen** [comment]
Ah!!!! Thank you so much!

With the react update helper, did you mean this one?
http://facebook.github.io/react/docs/update.html

**Comment by pieterv** [comment]
Yeah, thats the one.

**Comment by binarykitchen** [comment]
Thanks. All works perfect now.
