### ISSUE TITLE
TypeError: undefined in browser in Safari Version 8.0.3 (10600.3.18)

### ISSUE THREAD

**Issue by dannymk** [facebook/fixed-data-table#59]
Simply adding:
...
var FixedDataTable = require('fixed-data-table');
...

Produces this error in the browser:

TypeError: undefined is not a function (evaluating 'Object.assign(destination, propertyObjects[i])')

.... package.json
...
  "dependencies": {
    "fixed-data-table": "^0.1.1",
    "fluxxor": "^1.5.2",
    "react": "~0.12.2",
    "react-bootstrap": "^0.14.1",
    "react-router": "^0.11.6",
    "react-router-bootstrap": "^0.8.3"
  },
...

However, it works great in Firefox 35.0.1

**Comment by pieterv** [comment]
Hey @dannymk, You will need an ES6 compatible `Object.assign` polyfill. `'object-assign'` is a good one, you can then do `Object.assign = Object.assign || require('object-assign');` before you require `FixedDataTable` which should fix the problem.

**Comment by dannymk** [comment]
Thank you, I will give that a try.

**Comment by bkazmer** [comment]
Thank you, the fix works
