### ISSUE TITLE
Re-Renders when scrolling past the sides

### ISSUE THREAD

**Issue by matrinox** [facebook/fixed-data-table#61]
Seems inefficient to call `render` when the scroll position hasn't actually changed, even though the user is 'scrolling'

I've tested this by returning new data from `rowGetter` func such that `shouldComponentUpdate` in `FixedDataTableRow` always returns `false`

**Comment by ehzhang** [comment]
@matrinox could you clarify what you mean by this, and what performance costs you observe?

**Comment by matrinox** [comment]
@ehzhang This is what you need to do to reproduce:
1) Render component with
```jsx
<Table
  rowGetter={@rowGetter}
  …
  />
```
2) in `rowGetter` function, log the rowIndex/first param: `console.log(rowIndex)`
3) scroll to the top of the list and then keep scrolling

Notice that the logs keep coming even though clearly no rows have changed. In fact, I feel like it shouldn't bother calling that method unless a new row is really needed, as opposed to just on ever scroll. Performance cost isn't that high but could be better. It should only call it once when the user scrolls 1 pixel past the next row, versus all of them again.

**Comment by ehzhang** [comment]
Hmm! I just checked it out, and it looks like you're right - there are duplicate calls to the rowGetter function. However, if you add logs to a cellRenderer function, you'll notice that the cells themselves don't actually re-render.

The performance of the rowGetter is negligible, as the real bottleneck here is rendering. I've decided to close this issue as it is more of a micro-optimization.
