### ISSUE TITLE
Ways to style the table?

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#63]
Is there any way to pass `className` or `style` to table and cell components? I know I can attach CSS styles directly to generated elements and classes, but that's not very ideal because it generates hard linkings with inner workings of the component which should be opaque to the outside and is subject to changes.

**Comment by ofersadgat** [comment]
I think you can pass the props to the <Column> as part of the `columnData` and then use that in the cellRender to style your components.
