### ISSUE TITLE
Table keeps showing old data after re-rendering as if the whole table has been cached

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#68]
I'm using a pattern like this:

```javascript
const [matrix, columns] = generateData(this.props.data);

return <Table width = {400}
              height = {500}
              headerHeight = {36}
              rowHeight = {36}
              rowGetter = {x => matrix[x]}
              rowsCount = {matrix.length}
              overflowX = "hidden">
         {columns.map((v, k) => (
           <Column width = {100}
                   label = {v}
                   dataKey = {k} />
         ))}
       </Table>
```

And inside `generateData` I'll do a switch-case basing on some other state so that whenever this state changes, the columns will update accordingly. However, what I was seeing is that under seemingly random occasions, the table will just re-render with its previous data, as if the whole table has been cached. No warnings or errors whatsoever.

**Comment by gsklee** [comment]
Some more evidence about this being a bug of the lib:

This is what I saw using the React devtool:

![React Devtool](http://i.imgur.com/okdc8FI.png)

The correct figure after the update is `$13,872.17` as shown by the devtool, but the table/HTML displays `$0.00` which is the value before the update:

![HTML](http://i.imgur.com/66QHULb.png)

**Comment by pieterv** [comment]
@gsklee This is pretty weird, looks like it might be a lower level react problem, as from the screenshot it is rendering the correct value just the DOM is not being updated. Do you mind having a try at creating a simple repo case so i can dig into it? here is a good jsbin to start from: http://jsbin.com/valoco/5/edit?html,js,output.

**Comment by gsklee** [comment]
@pieterv I will see if I can come up with one this weekend when I get some time :)

**Comment by gsklee** [comment]
This is probably not a bug of the lib. Will reopen if such a case is confirmed.
