### ISSUE TITLE
cellRenderer (checkbox) in column does not re-render when using setState

### ISSUE THREAD

**Issue by dannymk** [facebook/fixed-data-table#70]
I can use jquery to keep the state in the browser and that works just fine.  However, I was looking for a react way and it seems I ran into a re-render issue in the fixed-data-table.
Is my thinking wrong?

See the original question here:  http://stackoverflow.com/questions/29067247/check-all-boxes-in-a-fixed-data-table-by-using/29090399

```html
'use strict';

var React = require('react/addons');
var Table = require('fixed-data-table').Table;
var Column = require('fixed-data-table').Column;

// Fixed data tables (Facebook) requirement:http://facebook.github.io/fixed-data-table/
require('../../styles/fixed-data-table.css');
var TableTester = React.createClass({
  getInitialState: function(){
    return ({
      selected:[],
      rows: [
        ['a1', 'b1', 'c1'],
        ['a2', 'b2', 'c2'],
        ['a3', 'b3', 'c3'],
      ]      
    })
  },
  render: function () {
    var data = this.state.rows;
    
    return (
      <div>
        <label>Check All</label>&nbsp;<input type="checkbox" onClick={this._checkall} />
        <Table rowsCount={data.length} rowGetter={this._rowGetter} width={1000} height={300} headerHeight={50} rowHeight={50}>
          <Column label="Col 1" width={500} dataKey={0} />                                                            
          <Column label="Col 2" width={500} dataKey={1} cellRenderer={this._renderCheckbox} align="center" />
        </Table>
      </div>
    );
  },
  
  _checkall:function(e){
    var newSet = [];
    if (e.target.checked) {
      this.state.rows.forEach(function(columns){
        newSet.push( columns[1] );
      });
    }
    this.setState({
      selected: newSet
    });
    
  },
  
  _onChange: function(e) {
    var {checked, value} = e.target;   
    var newSet = this.state.selected;
    if ( checked && newSet.indexOf(value) < 0 ) { // does not exist in list
      newSet.push(value);
    } else {
      newSet.splice(newSet.indexOf(value), 1);
    }  
    this.setState({
      selected: newSet
    });

  },  
  
  _renderCheckbox: function(data){
    var checked = this.state.selected.indexOf(data) >= 0; // value is in list  
    return <input type="checkbox" value={data} onChange={this._onChange} checked={checked} />;
  },
  
  _rowGetter: function(rowIndex){
      return this.state.rows[rowIndex];
  }
  
});

module.exports = TableTester;
```

**Comment by pieterv** [comment]
Hey @dannymk, the fixed data table applies a very aggressive shouldComponentUpdate function, which stops the `cellRenderer` from being called unless some data associated with that renderer has changed. The way we figure our what data is needed to render a row is via the `rowGetter`, so the issue above is that the state you are expecting to update your cellRenderer is not returned from the `rowGetter` so the diff does know that something has changed.

Here is an example of how it could work by embedding the data within the row object:
http://jsbin.com/temufa/18/edit

The other way to provide this behavior is for the cellRenderer to just return a single [react container](https://medium.com/@learnreact/container-components-c0e67432e005) which is responsible for subscribing to store data changes and updating the cell via setState. We do this for a lot of our applications but this only makes sense if for larger tables with a lot of different possible data types.

We are thinking about removing this aggressive shouldComponentUpdate functionality to make the table render more predictability but it will have a large performance cost if all cells rerender with each set update, so we are still trying to find the right balance here :)

**Comment by dannymk** [comment]
Thank you for your answer.   It helps a lot.  I look forward to to future version of this great component.

**Comment by mkrn** [comment]
@pieterv The container approach sounds pretty neat, it might work for us.
We are building a grid based on FixedDataTable that has edit mode  but initial performance is really bad on update in cells because it seem to re-render every cell for some reason, and it takes almost a second(

I've noticed some components in FixedDataTable are PureRender and some are not, including Table.

Do you have any examples out there for editable table? We are currently trying to subscribe every cell to store but it may be too many listeners too. Additionally it breaks the convention to subscribe to store change only in higher-level 'controller' components...

Any hint would be appreciated, thanks!

**Comment by steve-taylor** [comment]
> http://jsbin.com/temufa/18/edit

Doesn't work anymore.

**Comment by dannymk** [comment]
Steve, I just removed the "/** @jsx React.DOM */" at the top of your edit and it worked just fine.  What issues are you having?

**Comment by steve-taylor** [comment]
My edit? I didn't realise this was globally editable.

I landed here because I have the same or similar issue. I'm trying to implement spreadsheet-style editing in a FixedDataTable and came across this issue of the cell renderer not being invoked. I have read @pieterv's explanation and I'm working through a solution. What I'm trying to do is track the coordinates of the cell that is currently being edited and, when that changes, flip between a `div` and an `input`. The approach I'm going to take now is to create a non-singleton store to which the container components subscribe. The container components will be returned by the cell renderer.

**Comment by dannymk** [comment]
Sorry, can't help you there but I am glad you got it working.  I am swamped here and behind in quite a few projects.

**Comment by steve-taylor** [comment]
Yeah, thanks, I don't really need help now that I understand the container concept and how it can be used in my situation. Good luck with your projects. Sounds like you'll need it.

**Comment by jasongonzales23** [comment]
I don't see how this strategy applies when you are receiving the rows as props. Can you update your example to show how this might work?

Currently I am trying to get the toggling of a checkbox in a row to render, but can't figure it out. When I toggle, I can update state and see my component where the Table is receive nextProps, but the cell doesn't re-render properly. If I browse away and cause a re-render of the table though my checkboxes render their state accurately.

Here is some of the code
```javascript
        <Column
          align='center'
          width={60}
          dataKey={"isSelected"}
          headerRenderer={this.selectAllCheckbox}
          cellRenderer={this.renderCheckbox}
        />

  renderCheckbox(cellData, cellDataKey, rowData, rowIndex) {
    return (
      <input type="checkbox"
        onChange={this.toggleItem.bind(this, rowData)}
        checked={cellData}/>
    )
  }

  toggleItem(data) {
    if (data.isSelected) {
      this.props.deselectApp(data.id)
    } else {
      this.props.selectApp(data.id)
    }
  }

```

At this point, I'd take a hack or a workaround, been banging my head against the wall on this one for most of the day...

**Comment by jasongonzales23** [comment]
Interestingly, when I set a breakpoint in the `toggleItem` function, I can see the checkbox stays checked until some point in the event dispatching lifecycle. Is there a way to override that?

**Comment by Gongreg** [comment]
I found a workaround (since I didn't want to use stores or something else for single table), I had to add possibility to edit some row cells. So on button click I just changed that row data into new object with same values:

```js

  onEditClick(id, rowIndex) {

        //mock data change so row rerenders itself
        let filteredData = this.state.filteredData;
        filteredData[rowIndex] = {...filteredData[rowIndex]};

        this.setState({
            editingId: id,
            filteredData,
        });
    },

```
