### ISSUE TITLE
Is there a way to re-render Column header?

### ISSUE THREAD

**Issue by rovolution** [facebook/fixed-data-table#71]
hello!

I have a fixed data table, and am trying to add column sorting when a user clicks on a column header. I am using the ```headerRenderer``` property of Column to pass in a custom header rendering function. Within this function, I have an ```onClick``` handler on my header virtual element that tries to setState to re-render the view. However, the  methods I passed into ```headerRenderer``` are not re-triggering.

Is there anyway for me to get the Column headers to re-render after a call to ```setState```?

Thanks!

**Comment by pieterv** [comment]
@rovolution I created this example yesterday which shows how you can implement sorting which should help http://jsbin.com/temufa/10/edit?html,js,output

After not seeing to much detail my guess as to your problem is that the data your updating via setState is not being returned from the `headerDataGetter` and so the `headerRenderer` doesn't see the data has changed and doesn't update.

**Comment by rovolution** [comment]
thank you for the example @pieterv! I see that you are using the ```label``` property to get the arrow icon, which makes sense.

**Comment by pieterv** [comment]
Yes it was just simpler that way for this example but you can also pass more complex data via `headerDataGetter`, just remember if you want the cell to render the data returned needs to change :)

**Comment by rovolution** [comment]
cool yea just figured out how ```headerDataGetter``` works and that addressed my issue. thanks!

**Comment by Andreyco** [comment]
@rovolution  Could you please provide an example how you solved the issue?

I implemented custom `headerDataGetter` which return plain object. No matter what, header cell is not re-rendered, until one special case:

```jsx
// Not re-rendered
colProps.headerRenderer = this.renderHeaderSortingControls;

// Re-rendered
colProps.headerRenderer = () => {
    return this.renderHeaderSortingControls.apply(this, arguments);
};
```

**Comment by vegetableman** [comment]
But there are cases I would like to simply add a class to the header cell instead of content. Any suggestions for this use case?

**Comment by Andreyco** [comment]
You can specify `cellClassName` property on Column.
```js
var columns = [
  // ...
  {
    label: 'Buy',
    cellClassName: 'buy-column',
    // ....
  },
  // ...
];
```

Then, you can query this cell in header with simple selector, in this case with `.public_fixedDataTable_header .buy-column`

**Comment by mahimaag** [comment]
We can render any data on header of table simply by the headerRenderer props of Column like as below:
headerRenderer={(value) => <div className="pointer" onClick={handleHeaderClick.bind(event)}>This is your text.....</div>}
