### ISSUE TITLE
UMD/AMD support?

### ISSUE THREAD

**Issue by hipertracker** [facebook/fixed-data-table#78]
I can't use gulp/grunt processing and I don't want to load fixed-data-table and React as global objects. Id' like to load the library as AMD (or UMD) module. The problem is, files generated in dist/* by Webpack are not UMD/AMD compatible :(

**Comment by jnu** [comment]
you can use the [--output-library-target](http://webpack.github.io/docs/cli.html#configuration-options) option to webpack to bundle for amd/umd
