### ISSUE TITLE
Custom cellRenderer throws exceptions in React 0.13.x

### ISSUE THREAD

**Issue by caseywebdev** [facebook/fixed-data-table#83]
See: http://jsbin.com/zafubilame/1/edit?html,js,output

Change the react version to `0.12.2` and it works.

**Comment by jnu** [comment]
fwiw: https://github.com/facebook/react/issues/3396

**Comment by temnoregg** [comment]
I have updated react-tools dependency to 0.13.3 and rebuild and it works for me

**Comment by pieterv** [comment]
Sounds like this is a dependency issue, feel free to reopen if your still having trouble with the new version after reinstalling.
