### ISSUE TITLE
Do not "absorb" mouse scrolling if no scrollbar is visible

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#84]
It makes sense to prevent scroll events from propagating further up when there's a scrollbar in the table, but when there isn't one (ie. when the list isn't long enough), it makes sense to _not_ absorb the scroll events so there won't be an invisible mouse scrolling black hole on the page.

Scrolling your mouse wheel while the cursor is over a scrollbar-less table should scroll the page, making the table feel like an integrate part of the page.

**Comment by benshimmin** [comment]
Seconded. I just had to hack around this by drawing a giant invisible DIV rectangle all over the page so that the table, intentionally without scrollbars, didn't make the rest of the page non-scrollable.

**Comment by pieterv** [comment]
@gsklee @benshimmin Sorry we know this is bad and are planing on fixing this for the next release. For now a hacky fix for this if you know you don't need any scrolling is to set `overflowX="hidden"` `overflowY="hidden"` http://jsbin.com/valoco/12/edit.

**Comment by pieterv** [comment]
This should be fixed in the latest release :)

**Comment by gsklee** [comment]
@pieterv :100:
