### ISSUE TITLE
When the table is longer than the list, footer doesn't stick to the bottom of the table

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#97]
When table height > header height + rows height + footer height combined, footer will not stick to the bottom of the table which looks weird. See example: http://jsbin.com/yobeqojeqi/3/edit

**Comment by pieterv** [comment]
Hey @gsklee, thanks for the PR. Yeah this behavior is a little weird. So we have both `maxHeight` and `height` so our plan is to change `height` to make it work like you suggested (always stuck to the bottom) and then make sure `maxHeight` maintains the current behavior :)

**Comment by gsklee** [comment]
@pieterv cool :)

**Comment by pieterv** [comment]
They @gabelevi thanks for the PR we fixed this in 0.2.0 by allowing maxHeight or height which have the two different behaviors :)
